<?php

 /* $Id: $ */

if (TYPO3_MODE=="BE")   {
	require_once("../../../Resources/PHP/fpdf/fpdf.php");
} else {
	require_once("typo3conf/ext/mailformplusplus/Resources/PHP/fpdf/fpdf.php");
}

/**
 * A PDF Template class for MailformPlusPlus generated PDF files
 *
 * @author	Reinhard Führicht <rf@typoheads.at>
 * @package	F3_MailformPlusPlus
 * @subpackage	Utils
 */
class F3_MailformPlusPlus_Template_PDF extends FPDF {
    
	
	//Page header
	public function Header() {
	    
		//Arial bold 15
	    $this->SetFont('Arial','B',15);
	    
		//Title
	    $this->Cell(0,10,'Submission Details','B',0,'C');
	    
		//Line break
	    $this->Ln(20);
	}
	
	//Page footer
	public function Footer() {
	    
		//Position at 1.5 cm from bottom
	    $this->SetY(-15);
	    
		//Arial italic 8
	    $this->SetFont('Arial','I',8);
	    
	    $this->Cell(0,10,'Generated by MailformPlusPlus using FPDF at '.date("d.m.Y H:i:s",time()),'T',0,'C');
		$this->Cell(0,10,'Page '.$this->PageNo().'/{nb}','T',0,'R');
	}

}
?>
