mailformplusplus: F3_MailformPlusPlus_Validator_Default Class Reference
F3_MailformPlusPlus_Validator_Default Class Reference
Public Member Functions
validate ($gp, $settings, &$errors)
Protected Member Functions
validateMinFileSize (&$check, $name)
validateMaxFileSize (&$check, $name)
validateMaxFileCount (&$check, $name)
validateFileRequired (&$check, $name)
validateRequired (&$check, $name)
validateContainsNone ($check, $name)
validateEquals ($check, $name)
validateContainsOne ($check, $name)
validateContainsAll ($check, $name)
validateEmail (&$check, $name)
validateNotDefaultValue (&$check, $name)
validateInteger (&$check, $name)
validateFloat (&$check, $name)
validateMinValue (&$check, $name)
validateMaxValue (&$check, $name)
validateBetweenValue (&$check, $name)
validateMinLength (&$check, $name)
validateMaxLength (&$check, $name)
validateBetweenLength (&$check, $name)
validateMinItems (&$check, $name)
validateMaxItems (&$check, $name)
validateBetweenItems (&$check, $name)
validateIsInDBTable (&$check, $name)
validateIsNotInDBTable (&$check, $name)
validateEreg (&$check, $name)
validateEregi (&$check, $name)
validateCaptcha (&$check, $name)
validateSrFreecap (&$check, $name)
validateSimpleCaptcha (&$check, $name)
validateJmRecaptcha (&$check, $name)
validateMathGuard (&$check, $name)
validateTime (&$check, $name)
validateAllowedFileTypes (&$check, $name)
validateDate (&$check, $name)
validateDateRange (&$check, $name)
normalizeDatePattern ($pattern, $sep)
getCheckFailed ($check)
Detailed Description
Definition at line 41 of file F3_MailformPlusPlus_Validator_Default.php.
Member Function Documentation
F3_MailformPlusPlus_Validator_Default::getCheckFailed ($ check) [protected]
Sets the suitable string for the checkFailed message parsed in view.
Parameters:
array $check The parsed check settings
Returns:
string The check failed string
Definition at line 1151 of file F3_MailformPlusPlus_Validator_Default.php.
Referenced by validateAllowedFileTypes(), validateBetweenItems(), validateBetweenLength(), validateBetweenValue(), validateCaptcha(), validateContainsAll(), validateContainsNone(), validateContainsOne(), validateDate(), validateDateRange(), validateEmail(), validateEquals(), validateEreg(), validateEregi(), validateFileRequired(), validateFloat(), validateInteger(), validateIsInDBTable(), validateIsNotInDBTable(), validateJmRecaptcha(), validateMathGuard(), validateMaxFileCount(), validateMaxFileSize(), validateMaxItems(), validateMaxLength(), validateMaxValue(), validateMinFileSize(), validateMinItems(), validateMinLength(), validateMinValue(), validateNotDefaultValue(), validateRequired(), validateSimpleCaptcha(), validateSrFreecap(), and validateTime().
F3_MailformPlusPlus_Validator_Default::normalizeDatePattern ($ pattern, $ sep) [protected]
Internal method to normalize a specified date pattern for internal use
Parameters:
string $pattern The pattern
string $sep The seperator character
Returns:
string The normalized pattern
Definition at line 1133 of file F3_MailformPlusPlus_Validator_Default.php.
Referenced by validateDate(), and validateDateRange().
F3_MailformPlusPlus_Validator_Default::validate ($ gp, $ settings, &$ errors)
Validates the submitted values using given settings
Parameters:
array $gp The current GET/POST parameters
array $settings The TypoScript settings for the validator
array $errors Reference to the errors array to store the errors occurred
Returns:
boolean
Reimplemented from F3_MailformPlusPlus_AbstractValidator.
Definition at line 51 of file F3_MailformPlusPlus_Validator_Default.php.
References F3_MailformPlusPlus_AbstractValidator::$gp, validateAllowedFileTypes(), validateBetweenItems(), validateBetweenLength(), validateBetweenValue(), validateCaptcha(), validateContainsAll(), validateContainsNone(), validateContainsOne(), validateDate(), validateDateRange(), validateEmail(), validateEquals(), validateEreg(), validateEregi(), validateFileRequired(), validateFloat(), validateInteger(), validateIsInDBTable(), validateIsNotInDBTable(), validateJmRecaptcha(), validateMathGuard(), validateMaxFileCount(), validateMaxFileSize(), validateMaxItems(), validateMaxLength(), validateMaxValue(), validateMinFileSize(), validateMinItems(), validateMinLength(), validateMinValue(), validateNotDefaultValue(), validateRequired(), validateSimpleCaptcha(), validateSrFreecap(), and validateTime().
F3_MailformPlusPlus_Validator_Default::validateAllowedFileTypes (&$ check, $ name) [protected]
Validates that an uploaded file via specified field matches one of the given file types
Parameters:
array &$check The TypoScript settings for this error check
string $name The field name
Returns:
string The error string
Definition at line 1013 of file F3_MailformPlusPlus_Validator_Default.php.
References getCheckFailed().
Referenced by validate().
F3_MailformPlusPlus_Validator_Default::validateBetweenItems (&$ check, $ name) [protected]
Validates that a specified field is an array and has an item count between two specified values
Parameters:
array &$check The TypoScript settings for this error check
string $name The field name
Returns:
string The error string
Definition at line 790 of file F3_MailformPlusPlus_Validator_Default.php.
References getCheckFailed().
Referenced by validate().
F3_MailformPlusPlus_Validator_Default::validateBetweenLength (&$ check, $ name) [protected]
Validates that a specified field is a string and has a length between two specified values
Parameters:
array &$check The TypoScript settings for this error check
string $name The field name
Returns:
string The error string
Definition at line 729 of file F3_MailformPlusPlus_Validator_Default.php.
References getCheckFailed().
Referenced by validate().
F3_MailformPlusPlus_Validator_Default::validateBetweenValue (&$ check, $ name) [protected]
Validates that a specified field is an integer between two specified values
Parameters:
array &$check The TypoScript settings for this error check
string $name The field name
Returns:
string The error string
Definition at line 666 of file F3_MailformPlusPlus_Validator_Default.php.
References getCheckFailed().
Referenced by validate().
F3_MailformPlusPlus_Validator_Default::validateCaptcha (&$ check, $ name) [protected]
Validates that a specified field's value matches the generated word of the extension "captcha"
Parameters:
array &$check The TypoScript settings for this error check
string $name The field name
Returns:
string The error string
Definition at line 892 of file F3_MailformPlusPlus_Validator_Default.php.
References getCheckFailed().
Referenced by validate().
F3_MailformPlusPlus_Validator_Default::validateContainsAll ($ check, $ name) [protected]
Validates that a specified field contains all of the specified words
Parameters:
array &$check The TypoScript settings for this error check
string $name The field name
Returns:
string The error string
Definition at line 519 of file F3_MailformPlusPlus_Validator_Default.php.
References getCheckFailed().
Referenced by validate().
F3_MailformPlusPlus_Validator_Default::validateContainsNone ($ check, $ name) [protected]
Validates that a specified field doesn't contain one of the specified words
Parameters:
array &$check The TypoScript settings for this error check
string $name The field name
Returns:
string The error string
Definition at line 420 of file F3_MailformPlusPlus_Validator_Default.php.
References getCheckFailed().
Referenced by validate().
F3_MailformPlusPlus_Validator_Default::validateContainsOne ($ check, $ name) [protected]
Validates that a specified field contains at least one of the specified words
Parameters:
array &$check The TypoScript settings for this error check
string $name The field name
Returns:
string The error string
Definition at line 482 of file F3_MailformPlusPlus_Validator_Default.php.
References getCheckFailed().
Referenced by validate().
F3_MailformPlusPlus_Validator_Default::validateDate (&$ check, $ name) [protected]
Validates that a specified field's value is a valid date
Parameters:
array &$check The TypoScript settings for this error check
string $name The field name
Returns:
string The error string
Definition at line 1039 of file F3_MailformPlusPlus_Validator_Default.php.
References getCheckFailed(), and normalizeDatePattern().
Referenced by validate().
F3_MailformPlusPlus_Validator_Default::validateDateRange (&$ check, $ name) [protected]
Validates that a specified field's value is a valid date and between two specified dates
Parameters:
array &$check The TypoScript settings for this error check
string $name The field name
Returns:
string The error string
Definition at line 1074 of file F3_MailformPlusPlus_Validator_Default.php.
References getCheckFailed(), and normalizeDatePattern().
Referenced by validate().
F3_MailformPlusPlus_Validator_Default::validateEmail (&$ check, $ name) [protected]
Validates that a specified field has valid email syntax.
Parameters:
array &$check The TypoScript settings for this error check
string $name The field name
Returns:
string The error string
Definition at line 553 of file F3_MailformPlusPlus_Validator_Default.php.
References getCheckFailed().
Referenced by validate().
F3_MailformPlusPlus_Validator_Default::validateEquals ($ check, $ name) [protected]
Validates that a specified field equals a specified word
Parameters:
array &$check The TypoScript settings for this error check
string $name The field name
Returns:
string The error string
Definition at line 455 of file F3_MailformPlusPlus_Validator_Default.php.
References getCheckFailed().
Referenced by validate().
F3_MailformPlusPlus_Validator_Default::validateEreg (&$ check, $ name) [protected]
Validates that a specified field's value matches a regular expression
Parameters:
array &$check The TypoScript settings for this error check
string $name The field name
Returns:
string The error string
Definition at line 860 of file F3_MailformPlusPlus_Validator_Default.php.
References getCheckFailed().
Referenced by validate().
F3_MailformPlusPlus_Validator_Default::validateEregi (&$ check, $ name) [protected]
Validates that a specified field's value matches a regular expression case insensitive
Parameters:
array &$check The TypoScript settings for this error check
string $name The field name
Returns:
string The error string
Definition at line 876 of file F3_MailformPlusPlus_Validator_Default.php.
References getCheckFailed().
Referenced by validate().
F3_MailformPlusPlus_Validator_Default::validateFileRequired (&$ check, $ name) [protected]
Validates that a file gets uploaded via specified upload field
Parameters:
array &$check The TypoScript settings for this error check
string $name The field name
Returns:
string The error string
Definition at line 383 of file F3_MailformPlusPlus_Validator_Default.php.
References getCheckFailed().
Referenced by validate().
F3_MailformPlusPlus_Validator_Default::validateFloat (&$ check, $ name) [protected]
Validates that a specified field is a valid float
Parameters:
array &$check The TypoScript settings for this error check
string $name The field name
Returns:
string The error string
Definition at line 610 of file F3_MailformPlusPlus_Validator_Default.php.
References getCheckFailed().
Referenced by validate().
F3_MailformPlusPlus_Validator_Default::validateInteger (&$ check, $ name) [protected]
Validates that a specified field is a valid integer.
Parameters:
array &$check The TypoScript settings for this error check
string $name The field name
Returns:
string The error string
Definition at line 591 of file F3_MailformPlusPlus_Validator_Default.php.
References getCheckFailed().
Referenced by validate().
F3_MailformPlusPlus_Validator_Default::validateIsInDBTable (&$ check, $ name) [protected]
Validates that a specified field's value is found in a specified db table
Parameters:
array &$check The TypoScript settings for this error check
string $name The field name
Returns:
string The error string
Definition at line 813 of file F3_MailformPlusPlus_Validator_Default.php.
References getCheckFailed().
Referenced by validate().
F3_MailformPlusPlus_Validator_Default::validateIsNotInDBTable (&$ check, $ name) [protected]
Validates that a specified field's value is not found in a specified db table
Parameters:
array &$check The TypoScript settings for this error check
string $name The field name
Returns:
string The error string
Definition at line 836 of file F3_MailformPlusPlus_Validator_Default.php.
References getCheckFailed().
Referenced by validate().
F3_MailformPlusPlus_Validator_Default::validateJmRecaptcha (&$ check, $ name) [protected]
Validates that a specified field's value matches the generated word of the extension "jm_recaptcha"
Parameters:
array &$check The TypoScript settings for this error check
string $name The field name
Returns:
string The error string
Definition at line 951 of file F3_MailformPlusPlus_Validator_Default.php.
References getCheckFailed().
Referenced by validate().
F3_MailformPlusPlus_Validator_Default::validateMathGuard (&$ check, $ name) [protected]
Validates that a specified field's value matches the expected result of the MathGuard question
Parameters:
array &$check The TypoScript settings for this error check
string $name The field name
Returns:
string The error string
Definition at line 971 of file F3_MailformPlusPlus_Validator_Default.php.
References MathGuard::checkResult(), and getCheckFailed().
Referenced by validate().
F3_MailformPlusPlus_Validator_Default::validateMaxFileCount (&$ check, $ name) [protected]
Validates that up to x files get uploaded via the spcified upload field
Parameters:
array &$check The TypoScript settings for this error check
string $name The field name
Returns:
string The error string
Definition at line 352 of file F3_MailformPlusPlus_Validator_Default.php.
References getCheckFailed().
Referenced by validate().
F3_MailformPlusPlus_Validator_Default::validateMaxFileSize (&$ check, $ name) [protected]
Validates that an uploaded file has a maximum file size
Parameters:
array &$check The TypoScript settings for this error check
string $name The field name
Returns:
string The error string
Definition at line 330 of file F3_MailformPlusPlus_Validator_Default.php.
References getCheckFailed().
Referenced by validate().
F3_MailformPlusPlus_Validator_Default::validateMaxItems (&$ check, $ name) [protected]
Validates that a specified field is an array and has less than or exactly a specified amount of items
Parameters:
array &$check The TypoScript settings for this error check
string $name The field name
Returns:
string The error string
Definition at line 771 of file F3_MailformPlusPlus_Validator_Default.php.
References getCheckFailed().
Referenced by validate().
F3_MailformPlusPlus_Validator_Default::validateMaxLength (&$ check, $ name) [protected]
Validates that a specified field is a string and shorter a specified count of characters
Parameters:
array &$check The TypoScript settings for this error check
string $name The field name
Returns:
string The error string
Definition at line 708 of file F3_MailformPlusPlus_Validator_Default.php.
References getCheckFailed().
Referenced by validate().
F3_MailformPlusPlus_Validator_Default::validateMaxValue (&$ check, $ name) [protected]
Validates that a specified field is an integer and lower than or equal a specified value
Parameters:
array &$check The TypoScript settings for this error check
string $name The field name
Returns:
string The error string
Definition at line 646 of file F3_MailformPlusPlus_Validator_Default.php.
References getCheckFailed().
Referenced by validate().
F3_MailformPlusPlus_Validator_Default::validateMinFileSize (&$ check, $ name) [protected]
Validates that an uploaded file has a minimum file size
Parameters:
array &$check The TypoScript settings for this error check
string $name The field name
Returns:
string The error string
Definition at line 308 of file F3_MailformPlusPlus_Validator_Default.php.
References getCheckFailed().
Referenced by validate().
F3_MailformPlusPlus_Validator_Default::validateMinItems (&$ check, $ name) [protected]
Validates that a specified field is an array and has at least a specified amount of items
Parameters:
array &$check The TypoScript settings for this error check
string $name The field name
Returns:
string The error string
Definition at line 751 of file F3_MailformPlusPlus_Validator_Default.php.
References getCheckFailed().
Referenced by validate().
F3_MailformPlusPlus_Validator_Default::validateMinLength (&$ check, $ name) [protected]
Validates that a specified field is a string and at least a specified count of characters long
Parameters:
array &$check The TypoScript settings for this error check
string $name The field name
Returns:
string The error string
Definition at line 688 of file F3_MailformPlusPlus_Validator_Default.php.
References getCheckFailed().
Referenced by validate().
F3_MailformPlusPlus_Validator_Default::validateMinValue (&$ check, $ name) [protected]
Validates that a specified field is an integer and greater than or equal a specified value
Parameters:
array &$check The TypoScript settings for this error check
string $name The field name
Returns:
string The error string
Definition at line 626 of file F3_MailformPlusPlus_Validator_Default.php.
References getCheckFailed().
Referenced by validate().
F3_MailformPlusPlus_Validator_Default::validateNotDefaultValue (&$ check, $ name) [protected]
Validates that a specified field doesn't equal a specified default value. This default value could have been set via a PreProcessor.
Parameters:
array &$check The TypoScript settings for this error check
string $name The field name
Returns:
string The error string
Definition at line 570 of file F3_MailformPlusPlus_Validator_Default.php.
References getCheckFailed().
Referenced by validate().
F3_MailformPlusPlus_Validator_Default::validateRequired (&$ check, $ name) [protected]
Validates that a specified field is filled out
Parameters:
array &$check The TypoScript settings for this error check
string $name The field name
Returns:
string The error string
Definition at line 405 of file F3_MailformPlusPlus_Validator_Default.php.
References getCheckFailed().
Referenced by validate().
F3_MailformPlusPlus_Validator_Default::validateSimpleCaptcha (&$ check, $ name) [protected]
Validates that the correct image of possible images displayed by the extension "simple_captcha" got selected.
Parameters:
array &$check The TypoScript settings for this error check
string $name The field name
Returns:
string The error string
Definition at line 931 of file F3_MailformPlusPlus_Validator_Default.php.
References getCheckFailed().
Referenced by validate().
F3_MailformPlusPlus_Validator_Default::validateSrFreecap (&$ check, $ name) [protected]
Validates that a specified field's value matches the generated word of the extension "sr_freecap"
Parameters:
array &$check The TypoScript settings for this error check
string $name The field name
Returns:
string The error string
Definition at line 912 of file F3_MailformPlusPlus_Validator_Default.php.
References getCheckFailed().
Referenced by validate().
F3_MailformPlusPlus_Validator_Default::validateTime (&$ check, $ name) [protected]
Validates that a specified field's value is a valid time
Parameters:
array &$check The TypoScript settings for this error check
string $name The field name
Returns:
string The error string
Definition at line 987 of file F3_MailformPlusPlus_Validator_Default.php.
References getCheckFailed().
Referenced by validate().