mailformplusplus: F3_MailformPlusPlus_StaticFuncs_testcase Class Reference
F3_MailformPlusPlus_StaticFuncs_testcase Class Reference
Public Member Functions
test_getDocumentRoot ()
test_getHostname ()
test_sanitizePath ()
test_getFilledLangMarkers ()
test_getFilledValueMarkers ()
test_removeUnfilledMarkers ()
test_resolvePath ()
test_resolveRelPath ()
Protected Member Functions
setUp ()
tearDown ()
Protected Attributes
$components
$repository
Detailed Description
Definition at line 23 of file F3_MailformPlusPlus_StaticFuncs_testcase.php.
Member Function Documentation
F3_MailformPlusPlus_StaticFuncs_testcase::setUp () [protected]
Definition at line 28 of file F3_MailformPlusPlus_StaticFuncs_testcase.php.
F3_MailformPlusPlus_StaticFuncs_testcase::tearDown () [protected]
Definition at line 32 of file F3_MailformPlusPlus_StaticFuncs_testcase.php.
F3_MailformPlusPlus_StaticFuncs_testcase::test_getDocumentRoot ()
Definition at line 35 of file F3_MailformPlusPlus_StaticFuncs_testcase.php.
References F3_MailformPlusPlus_StaticFuncs::getDocumentRoot().
F3_MailformPlusPlus_StaticFuncs_testcase::test_getFilledLangMarkers ()
Definition at line 54 of file F3_MailformPlusPlus_StaticFuncs_testcase.php.
References F3_MailformPlusPlus_StaticFuncs::getFilledLangMarkers().
F3_MailformPlusPlus_StaticFuncs_testcase::test_getFilledValueMarkers ()
Definition at line 73 of file F3_MailformPlusPlus_StaticFuncs_testcase.php.
References F3_MailformPlusPlus_StaticFuncs::getFilledValueMarkers().
F3_MailformPlusPlus_StaticFuncs_testcase::test_getHostname ()
Definition at line 39 of file F3_MailformPlusPlus_StaticFuncs_testcase.php.
References F3_MailformPlusPlus_StaticFuncs::getHostname().
F3_MailformPlusPlus_StaticFuncs_testcase::test_removeUnfilledMarkers ()
Definition at line 83 of file F3_MailformPlusPlus_StaticFuncs_testcase.php.
References F3_MailformPlusPlus_StaticFuncs::removeUnfilledMarkers().
F3_MailformPlusPlus_StaticFuncs_testcase::test_resolvePath ()
Definition at line 88 of file F3_MailformPlusPlus_StaticFuncs_testcase.php.
References F3_MailformPlusPlus_StaticFuncs::getDocumentRoot(), and F3_MailformPlusPlus_StaticFuncs::resolvePath().
F3_MailformPlusPlus_StaticFuncs_testcase::test_resolveRelPath ()
Definition at line 95 of file F3_MailformPlusPlus_StaticFuncs_testcase.php.
References F3_MailformPlusPlus_StaticFuncs::resolveRelPath().
F3_MailformPlusPlus_StaticFuncs_testcase::test_sanitizePath ()
Definition at line 43 of file F3_MailformPlusPlus_StaticFuncs_testcase.php.
References F3_MailformPlusPlus_StaticFuncs::sanitizePath().
Member Data Documentation
F3_MailformPlusPlus_StaticFuncs_testcase::$components [protected]
Definition at line 25 of file F3_MailformPlusPlus_StaticFuncs_testcase.php.
F3_MailformPlusPlus_StaticFuncs_testcase::$repository [protected]
Definition at line 26 of file F3_MailformPlusPlus_StaticFuncs_testcase.php.