mailformplusplus: F3_MailformPlusPlus_Finisher_StoreUploadedFiles Class Reference
F3_MailformPlusPlus_Finisher_StoreUploadedFiles Class Reference
Inherits F3_MailformPlusPlus_AbstractFinisher.
Public Member Functions
process ()
Protected Member Functions
moveUploadedFiles ()
getNewFilename ($oldName)
Detailed Description
Definition at line 37 of file F3_MailformPlusPlus_Finisher_StoreUploadedFiles.php.
Member Function Documentation
F3_MailformPlusPlus_Finisher_StoreUploadedFiles::getNewFilename ($ oldName) [protected]
Generates a new filename for an uploaded file using settings in TypoScript.
Parameters:
string The current filename
Returns:
string The new filename
Definition at line 109 of file F3_MailformPlusPlus_Finisher_StoreUploadedFiles.php.
Referenced by moveUploadedFiles().
F3_MailformPlusPlus_Finisher_StoreUploadedFiles::moveUploadedFiles () [protected]
Moves uploaded files from temporary upload folder to a specified new folder. This enables you to move the files from a successful submission to another folder and clean the files in temporary upload folder from time to time.
TypoScript example:
1. Set the temporary upload folder and set cleaning plugin.F3_MailformPlusPlus.settings.files.clearTempFilesOlderThanHours = 24 plugin.F3_MailformPlusPlus.settings.files.tmpUploadFolder = uploads/mailformplusplus/tmp
2. Set the folder to move the files to after submission plugin.F3_MailformPlusPlus.settings.finishers.1.class = F3_MailformPlusPlus_Finisher_StoreUploadedFiles plugin.F3_MailformPlusPlus.settings.finishers.1.config.finishedUploadFolder = uploads/mailformplusplus/finishedFiles/ plugin.F3_MailformPlusPlus.settings.finishers.1.config.renameScheme = [filename]_[md5]_[time]
Returns:
void
Definition at line 76 of file F3_MailformPlusPlus_Finisher_StoreUploadedFiles.php.
References F3_MailformPlusPlus_StaticFuncs::debugMessage(), F3_MailformPlusPlus_StaticFuncs::getDocumentRoot(), getNewFilename(), and F3_MailformPlusPlus_StaticFuncs::sanitizePath().
Referenced by process().
F3_MailformPlusPlus_Finisher_StoreUploadedFiles::process ()
The main method called by the controller
Returns:
array The probably modified GET/POST parameters
Reimplemented from F3_MailformPlusPlus_AbstractFinisher.
Definition at line 44 of file F3_MailformPlusPlus_Finisher_StoreUploadedFiles.php.
References moveUploadedFiles().