MailformPlusPlus: F3_MailformPlusPlus_PreProcessor_LoadDefaultValues Class Reference
F3_MailformPlusPlus_PreProcessor_LoadDefaultValues Class Reference
Inherits F3_MailformPlusPlus_AbstractPreProcessor.
Public Member Functions
process ($gp, $settings)
loadDefaultValuesToGP ($settings)
Private Member Functions
loadDefaultValuesToSession ($settings, $step)
Detailed Description
Definition at line 47 of file F3_MailformPlusPlus_PreProcessor_LoadDefaultValues.php.
Member Function Documentation
F3_MailformPlusPlus_PreProcessor_LoadDefaultValues::loadDefaultValuesToGP ($ settings)
adapted from class tx_thmailformplus_pi1 Loads the default values to the GP Array
Returns:
void
Parameters:
array $settings
Definition at line 72 of file F3_MailformPlusPlus_PreProcessor_LoadDefaultValues.php.
Referenced by process().
F3_MailformPlusPlus_PreProcessor_LoadDefaultValues::loadDefaultValuesToSession ($ settings, $ step) [private]
loads the Default Setting in the Session. Used only for step 2+.
Returns:
void
Parameters:
Array $settings
int $step
Definition at line 99 of file F3_MailformPlusPlus_PreProcessor_LoadDefaultValues.php.
Referenced by process().
F3_MailformPlusPlus_PreProcessor_LoadDefaultValues::process ($ gp, $ settings)
Main method called by the controller.
Parameters:
array $gp The current GET/POST parameters
array $settings The settings for the logger
Returns:
array The probably modified GET/POST parameters
Reimplemented from F3_MailformPlusPlus_AbstractPreProcessor.
Definition at line 49 of file F3_MailformPlusPlus_PreProcessor_LoadDefaultValues.php.
References F3_MailformPlusPlus_AbstractPreProcessor::$gp, loadDefaultValuesToGP(), and loadDefaultValuesToSession().