mailformplusplus: F3_MailformPlusPlus_Finisher_Mail Class Reference
F3_MailformPlusPlus_Finisher_Mail Class Reference
Inherits F3_MailformPlusPlus_AbstractFinisher.
Public Member Functions
process ()
loadConfig ($gp, $tsConfig)
validateConfig ()
Protected Member Functions
parseTemplate ($mode, $suffix)
sanitizeMarkers (&$markers)
getTemplate ()
sendMail ($type)
fillLangMarkersInSettings (&$settings)
getSettings ()
init ()
parseEmailSettings ($tsConfig)
Private Member Functions
explodeList ($list, $sep=",")
parseSettingValue ($value)
parseValue ($settings, $type, $key)
parseList ($settings, $type, $key)
parseFilesList ($settings, $type, $key)
parseEmailSettingsByType ($currentSettings, $type, $optionsToParse=array())
Detailed Description
Definition at line 68 of file F3_MailformPlusPlus_Finisher_Mail.php.
Member Function Documentation
F3_MailformPlusPlus_Finisher_Mail::explodeList ($ list, $ sep = ",") [private]
Explodes the given list seperated by $sep. Substitutes values with according value in GET/POST, if set.
Parameters:
string $list
string $sep
Returns:
array
Definition at line 297 of file F3_MailformPlusPlus_Finisher_Mail.php.
Referenced by parseList().
F3_MailformPlusPlus_Finisher_Mail::fillLangMarkersInSettings (&$ settings) [protected]
Substitutes markers like ##LLL:langKey### in given TypoScript settings array.
Parameters:
array &$settings The E-Mail settings
Returns:
void
Definition at line 402 of file F3_MailformPlusPlus_Finisher_Mail.php.
References F3_MailformPlusPlus_AbstractFinisher::$settings, and F3_MailformPlusPlus_StaticFuncs::getFilledLangMarkers().
Referenced by parseEmailSettingsByType().
F3_MailformPlusPlus_Finisher_Mail::getSettings () [protected]
Fetches the global TypoScript settings of the MailformPlusPlus
Returns:
void
Definition at line 420 of file F3_MailformPlusPlus_Finisher_Mail.php.
F3_MailformPlusPlus_Finisher_Mail::getTemplate () [protected]
Parses the globally defined template file for E-mail template with given mode and suffix
Parameters:
string $mode user/admin
string $suffix plain/html
Returns:
string The template code
Definition at line 153 of file F3_MailformPlusPlus_Finisher_Mail.php.
References F3_MailformPlusPlus_StaticFuncs::resolvePath().
Referenced by parseTemplate().
F3_MailformPlusPlus_Finisher_Mail::init () [protected]
Inits the finisher mapping settings values to internal attributes.
Returns:
void
Definition at line 429 of file F3_MailformPlusPlus_Finisher_Mail.php.
References F3_MailformPlusPlus_StaticFuncs::resolvePath().
Referenced by process().
F3_MailformPlusPlus_Finisher_Mail::loadConfig ($ gp, $ tsConfig)
Method to set GET/POST for this class and load the configuration
Parameters:
array The GET/POST values
array The TypoScript configuration
Returns:
void
Reimplemented from F3_MailformPlusPlus_AbstractFinisher.
Definition at line 446 of file F3_MailformPlusPlus_Finisher_Mail.php.
References F3_MailformPlusPlus_AbstractFinisher::$gp, parseEmailSettings(), and F3_MailformPlusPlus_StaticFuncs::pi_getFFvalue().
F3_MailformPlusPlus_Finisher_Mail::parseEmailSettings ($ tsConfig) [protected]
Parses the email settings in flexform and stores them in an array.
Parameters:
array The TypoScript configuration
Returns:
array The parsed email settings
Definition at line 483 of file F3_MailformPlusPlus_Finisher_Mail.php.
References parseEmailSettingsByType().
Referenced by loadConfig().
F3_MailformPlusPlus_Finisher_Mail::parseEmailSettingsByType ($ currentSettings, $ type, $ optionsToParse = array()) [private]
Parses the email settings in flexform of a specific type (admin|user]
Parameters:
array $currentSettings The current settings array containing the settings made via TypoScript
string $type (admin|user)
array $optionsToParse Array containing all option names to parse.
Returns:
array The parsed email settings
Definition at line 521 of file F3_MailformPlusPlus_Finisher_Mail.php.
References fillLangMarkersInSettings(), parseFilesList(), parseList(), parseValue(), F3_MailformPlusPlus_StaticFuncs::pi_getFFvalue(), and F3_MailformPlusPlus_StaticFuncs::prepareClassName().
Referenced by parseEmailSettings().
F3_MailformPlusPlus_Finisher_Mail::parseFilesList ($ settings, $ type, $ key) [private]
Parses a list of file names or field names set in TypoScript and overrides it with setting in plugin record if set.
Parameters:
array $settings The settings array containing the mail settings
string $type admin|user
string $key The key to parse in the settings array
Returns:
string
Definition at line 374 of file F3_MailformPlusPlus_Finisher_Mail.php.
References F3_MailformPlusPlus_AbstractFinisher::$settings.
Referenced by parseEmailSettingsByType().
F3_MailformPlusPlus_Finisher_Mail::parseList ($ settings, $ type, $ key) [private]
Parses a setting in TypoScript and overrides it with setting in plugin record if set. The settings contains a list of values or a TS object.
Parameters:
array $settings The settings array containing the mail settings
string $type admin|user
string $key The key to parse in the settings array
Returns:
string|array
Definition at line 355 of file F3_MailformPlusPlus_Finisher_Mail.php.
References F3_MailformPlusPlus_AbstractFinisher::$settings, and explodeList().
Referenced by parseEmailSettingsByType().
F3_MailformPlusPlus_Finisher_Mail::parseSettingValue ($ value) [private]
Substitutes values with according value in GET/POST, if set.
Parameters:
string $value
Returns:
string
Definition at line 316 of file F3_MailformPlusPlus_Finisher_Mail.php.
Referenced by parseValue().
F3_MailformPlusPlus_Finisher_Mail::parseTemplate ($ mode, $ suffix) [protected]
Returns the final template code for given mode and suffix with substituted markers.
Parameters:
string $mode user/admin
string $suffix plain/html
Returns:
string The template code
Definition at line 94 of file F3_MailformPlusPlus_Finisher_Mail.php.
References F3_MailformPlusPlus_StaticFuncs::debugMessage(), and getTemplate().
Referenced by sendMail().
F3_MailformPlusPlus_Finisher_Mail::parseValue ($ settings, $ type, $ key) [private]
Parses a setting in TypoScript and overrides it with setting in plugin record if set. The settings contains a single value or a TS object.
Parameters:
array $settings The settings array containing the mail settings
string $type admin|user
string $key The key to parse in the settings array
Returns:
string
Definition at line 335 of file F3_MailformPlusPlus_Finisher_Mail.php.
References F3_MailformPlusPlus_AbstractFinisher::$settings, and parseSettingValue().
Referenced by parseEmailSettingsByType().
F3_MailformPlusPlus_Finisher_Mail::process ()
The main method called by the controller
Returns:
array The probably modified GET/POST parameters
Reimplemented from F3_MailformPlusPlus_AbstractFinisher.
Definition at line 75 of file F3_MailformPlusPlus_Finisher_Mail.php.
References init(), and sendMail().
F3_MailformPlusPlus_Finisher_Mail::sanitizeMarkers (&$ markers) [protected]
Sanitizes E-mail markers by processing the 'checkBinaryCrLf' setting in TypoScript
Parameters:
array &$markers The E-mail markers
Returns:
void
Definition at line 122 of file F3_MailformPlusPlus_Finisher_Mail.php.
F3_MailformPlusPlus_Finisher_Mail::sendMail ($ type) [protected]
Sends mail according to given type.
Parameters:
string $type (admin|user)
Returns:
void
Definition at line 171 of file F3_MailformPlusPlus_Finisher_Mail.php.
References F3_MailformPlusPlus_StaticFuncs::debugMessage(), and parseTemplate().
Referenced by process().
F3_MailformPlusPlus_Finisher_Mail::validateConfig ()
Method to define whether the config is valid or not. If no, an exception is thrown.
Reimplemented from F3_MailformPlusPlus_AbstractFinisher.
Definition at line 471 of file F3_MailformPlusPlus_Finisher_Mail.php.
References F3_MailformPlusPlus_StaticFuncs::throwException().