mailformplusplus: F3_MailformPlusPlus_AbstractView Class Reference
F3_MailformPlusPlus_AbstractView Class Reference
Inherited by F3_MailformPlusPlus_View_Default, and F3_MailformPlusPlus_View_Listing.
Public Member Functions
__construct (F3_GimmeFive_Component_Manager $componentManager, F3_MailformPlusPlus_Configuration $configuration)
setLangFile ($langFile)
setSettings ($settings)
setPredefined ($key)
setModel ($model)
getModel ()
setTemplate ($templateCode, $templateName, $forceTemplate=FALSE)
render ($gp, $errors)
Public Attributes
$prefixId = 'F3_MailformPlusPlus'
$extKey = 'mailformplusplus'
$cObj
$piVars
Protected Member Functions
initializeView ()
fillMarker ($term, &$markerArray, &$wrappedSubpartArray)
getUpperCase ($camelCase)
Protected Attributes
$componentManager
$configuration
$model
$subparts
$typolinkConf
$template
$langFile
$gp
$xajax
Detailed Description
Definition at line 22 of file F3_MailformPlusPlus_AbstractView.php.
Constructor & Destructor Documentation
F3_MailformPlusPlus_AbstractView::__construct (F3_GimmeFive_Component_Manager $ componentManager, F3_MailformPlusPlus_Configuration $ configuration)
The constructor for a view setting the component manager and the configuration.
Parameters:
F3_GimmeFive_Component_Manager $componentManager
F3_MailformPlusPlus_Configuration $configuration
Returns:
void
Definition at line 135 of file F3_MailformPlusPlus_AbstractView.php.
References $typolinkConf, and initializeView().
Member Function Documentation
F3_MailformPlusPlus_AbstractView::fillMarker ($ term, &$ markerArray, &$ wrappedSubpartArray) [protected]
Fills markers in template
Returns:
void
Author:
Jochen Rau
Definition at line 238 of file F3_MailformPlusPlus_AbstractView.php.
References getUpperCase().
F3_MailformPlusPlus_AbstractView::getModel ()
Returns the model of the view
Returns:
misc $model
Definition at line 196 of file F3_MailformPlusPlus_AbstractView.php.
References $model.
F3_MailformPlusPlus_AbstractView::getUpperCase ($ camelCase) [protected]
Returns given string in uppercase
Parameters:
string $camelCase The string to transform
Returns:
string Parsed string
Author:
Jochen Rau
Definition at line 259 of file F3_MailformPlusPlus_AbstractView.php.
Referenced by fillMarker().
F3_MailformPlusPlus_AbstractView::initializeView () [protected]
Overwrite this method to extend the initialization of the View
Returns:
void
Author:
Jochen Rau
Definition at line 229 of file F3_MailformPlusPlus_AbstractView.php.
Referenced by __construct().
F3_MailformPlusPlus_AbstractView::render ($ gp, $ errors) [abstract]
This method performs the rendering of the view
Parameters:
array $gp The get/post parameters
array $errors An array with errors occurred whilest validation
Returns:
rendered view
Reimplemented in F3_MailformPlusPlus_View_Confirmation, F3_MailformPlusPlus_View_Default, and F3_MailformPlusPlus_View_Listing.
F3_MailformPlusPlus_AbstractView::setLangFile ($ langFile)
Sets the internal attribute "langFile"
Parameters:
string $langFile The file path
Returns:
void
Definition at line 157 of file F3_MailformPlusPlus_AbstractView.php.
References $langFile.
F3_MailformPlusPlus_AbstractView::setModel ($ model)
Sets the model of the view
Parameters:
misc $model
Returns:
void
Definition at line 187 of file F3_MailformPlusPlus_AbstractView.php.
References $model.
F3_MailformPlusPlus_AbstractView::setPredefined ($ key)
Sets the key of the chosen predefined form
Parameters:
string $key The key of the predefined form
Returns:
void
Definition at line 177 of file F3_MailformPlusPlus_AbstractView.php.
F3_MailformPlusPlus_AbstractView::setSettings ($ settings)
Sets the settings
Parameters:
string $settings The settings
Returns:
void
Definition at line 167 of file F3_MailformPlusPlus_AbstractView.php.
F3_MailformPlusPlus_AbstractView::setTemplate ($ templateCode, $ templateName, $ forceTemplate = FALSE)
Sets the template of the view
Parameters:
string $templateCode The whole template code of a template file
string $templateName Name of a subpart containing the template code to work with
boolean $forceTemplate Not needed
Returns:
void
Definition at line 208 of file F3_MailformPlusPlus_AbstractView.php.
Member Data Documentation
F3_MailformPlusPlus_AbstractView::$cObj
Definition at line 46 of file F3_MailformPlusPlus_AbstractView.php.
F3_MailformPlusPlus_AbstractView::$componentManager [protected]
Definition at line 62 of file F3_MailformPlusPlus_AbstractView.php.
F3_MailformPlusPlus_AbstractView::$configuration [protected]
Definition at line 70 of file F3_MailformPlusPlus_AbstractView.php.
F3_MailformPlusPlus_AbstractView::$extKey = 'mailformplusplus'
Definition at line 38 of file F3_MailformPlusPlus_AbstractView.php.
F3_MailformPlusPlus_AbstractView::$gp [protected]
Definition at line 118 of file F3_MailformPlusPlus_AbstractView.php.
Referenced by F3_MailformPlusPlus_View_Default::render(), and F3_MailformPlusPlus_View_Confirmation::render().
F3_MailformPlusPlus_AbstractView::$langFile [protected]
Definition at line 110 of file F3_MailformPlusPlus_AbstractView.php.
Referenced by F3_MailformPlusPlus_View_Default::fillCaptchaMarkers(), and setLangFile().
F3_MailformPlusPlus_AbstractView::$model [protected]
Definition at line 78 of file F3_MailformPlusPlus_AbstractView.php.
Referenced by getModel(), and setModel().
F3_MailformPlusPlus_AbstractView::$piVars
Definition at line 54 of file F3_MailformPlusPlus_AbstractView.php.
F3_MailformPlusPlus_AbstractView::$prefixId = 'F3_MailformPlusPlus'
Definition at line 30 of file F3_MailformPlusPlus_AbstractView.php.
F3_MailformPlusPlus_AbstractView::$subparts [protected]
Definition at line 86 of file F3_MailformPlusPlus_AbstractView.php.
F3_MailformPlusPlus_AbstractView::$template [protected]
Definition at line 102 of file F3_MailformPlusPlus_AbstractView.php.
F3_MailformPlusPlus_AbstractView::$typolinkConf [protected]
Definition at line 94 of file F3_MailformPlusPlus_AbstractView.php.
Referenced by __construct().
F3_MailformPlusPlus_AbstractView::$xajax [protected]
Definition at line 126 of file F3_MailformPlusPlus_AbstractView.php.