MailformPlusPlus: F3_MailformPlusPlus_Finisher_StoreGP Class Reference
F3_MailformPlusPlus_Finisher_StoreGP Class Reference
Inherits F3_MailformPlusPlus_AbstractFinisher.
Public Member Functions
process ()
Protected Member Functions
storeUserGPinSession ()
updateSession ()
Detailed Description
Definition at line 27 of file F3_MailformPlusPlus_Finisher_StoreGP.php.
Member Function Documentation
F3_MailformPlusPlus_Finisher_StoreGP::process ()
The main method called by the controller
Returns:
array The probably modified GET/POST parameters
Reimplemented from F3_MailformPlusPlus_AbstractFinisher.
Definition at line 34 of file F3_MailformPlusPlus_Finisher_StoreGP.php.
References storeUserGPinSession(), and updateSession().
F3_MailformPlusPlus_Finisher_StoreGP::storeUserGPinSession () [protected]
Stores the GP in session.
Returns:
void
Definition at line 50 of file F3_MailformPlusPlus_Finisher_StoreGP.php.
Referenced by process().
F3_MailformPlusPlus_Finisher_StoreGP::updateSession () [protected]
Stores $this->gp parameters in SESSION actually only needed for finisher_confirmation
Returns:
void
Definition at line 62 of file F3_MailformPlusPlus_Finisher_StoreGP.php.
Referenced by process().