mailformplusplus: F3_MailformPlusPlus_StaticFuncs Class Reference
F3_MailformPlusPlus_StaticFuncs Class Reference
Static Public Member Functions
static getDocumentRoot ()
static getTYPO3Root ()
static prepareClassName ($className)
static substituteMarkerArray ($content, $markContentArray)
static getSubpart ($content, $marker)
static pi_getFFvalue ($T3FlexForm_array, $fieldName, $sheet='sDEF', $lang='lDEF', $value='vDEF')
static dateToTimestamp ($date, $end=false)
static getHostname ()
static sanitizePath ($path)
static convertToRelativePath ($absPath)
static getFilledLangMarkers (&$template, $langFile)
static getFilledValueMarkers (&$gp)
static reverse_htmlspecialchars ($mixed)
static debugMessage ($key)
static throwException ($key)
static debugArray ($arr)
static removeUnfilledMarkers ($content)
static resolvePath ($path)
static resolveRelPath ($path)
static resolveRelPathFromSiteRoot ($path)
Static Public Attributes
static $cObj
Static Private Member Functions
static pi_getFFvalueFromSheetArray ($sheetArray, $fieldNameArr, $value)
Detailed Description
Definition at line 24 of file F3_MailformPlusPlus_StaticFuncs.php.
Member Function Documentation
static F3_MailformPlusPlus_StaticFuncs::convertToRelativePath ($ absPath) [static]
Converts an absolute path into a relative path from TYPO3 root directory.
Example:
IN : C:/xampp/htdocs/typo3/fileadmin/file.html OUT : fileadmin/file.html
Parameters:
string $template The template code
string $langFile The path to the language file
Returns:
array The filled language markers
Definition at line 230 of file F3_MailformPlusPlus_StaticFuncs.php.
Referenced by F3_MailformPlusPlus_Controller_Default::readLanguageFile().
static F3_MailformPlusPlus_StaticFuncs::dateToTimestamp ($ date, $ end = false) [static]
This function formats a date
Parameters:
long $date The timestamp to format
boolean $end Is end date or start date
Returns:
string formatted date
Author:
Reinhard Führicht <rf@typoheads.at>
Definition at line 178 of file F3_MailformPlusPlus_StaticFuncs.php.
Referenced by F3_MailformPlusPlus_Controller_Backend::buildWhereClause().
static F3_MailformPlusPlus_StaticFuncs::debugArray ($ arr) [static]
Method to print the contents of an array
Parameters:
array $arr The array to print
Returns:
void
Definition at line 366 of file F3_MailformPlusPlus_StaticFuncs.php.
Referenced by F3_MailformPlusPlus_Controller_Multistep::process().
static F3_MailformPlusPlus_StaticFuncs::debugMessage ($ key) [static]
Method to print a debug message to screen
Parameters:
string $message The message to print
boolean $extended Print a header style message or default output
Returns:
void
Definition at line 320 of file F3_MailformPlusPlus_StaticFuncs.php.
References F3_MailformPlusPlus_Messages::getDebugMessage().
Referenced by F3_MailformPlusPlus_Controller_Default::addSpecialJS(), F3_MailformPlusPlus_Controller_Default::clearSession(), F3_MailformPlusPlus_Controller_Default::clearTempFiles(), F3_MailformPlusPlus_Controller_Default::getTempUploadFolder(), F3_MailformPlusPlus_Logger_DB::log(), tx_MailformPlusPlus_Dispatcher::main(), F3_MailformPlusPlus_View_Default::markersCountAsSet(), F3_MailformPlusPlus_Finisher_StoreUploadedFiles::moveUploadedFiles(), F3_MailformPlusPlus_Finisher_Mail::parseTemplate(), F3_MailformPlusPlus_Finisher_DB::process(), F3_MailformPlusPlus_Controller_Multistep::process(), F3_MailformPlusPlus_Controller_Default::process(), F3_MailformPlusPlus_Controller_Default::processFiles(), F3_MailformPlusPlus_Controller_Default::runClasses(), F3_MailformPlusPlus_Finisher_DifferentDB::save(), F3_MailformPlusPlus_Finisher_DB::save(), F3_MailformPlusPlus_Finisher_Mail::sendMail(), F3_MailformPlusPlus_Interceptor_IPBlocking::sendReport(), F3_MailformPlusPlus_Controller_Multistep::setViewSubpart(), and F3_MailformPlusPlus_Validator_Default::validate().
static F3_MailformPlusPlus_StaticFuncs::getDocumentRoot () [static]
Returns the absolute path to the document root
Returns:
string
Definition at line 39 of file F3_MailformPlusPlus_StaticFuncs.php.
Referenced by F3_MailformPlusPlus_Controller_Default::clearTempFiles(), F3_MailformPlusPlus_Finisher_StoreUploadedFiles::moveUploadedFiles(), F3_MailformPlusPlus_StaticFuncs_testcase::test_getDocumentRoot(), and F3_MailformPlusPlus_StaticFuncs_testcase::test_resolvePath().
static F3_MailformPlusPlus_StaticFuncs::getFilledLangMarkers (&$ template, $ langFile) [static]
Finds and fills language markers in given template code.
Parameters:
string $template The template code
string $langFile The path to the language file
Returns:
array The filled language markers
Definition at line 250 of file F3_MailformPlusPlus_StaticFuncs.php.
Referenced by F3_MailformPlusPlus_Finisher_Mail::fillLangMarkersInSettings(), and F3_MailformPlusPlus_StaticFuncs_testcase::test_getFilledLangMarkers().
static F3_MailformPlusPlus_StaticFuncs::getFilledValueMarkers (&$ gp) [static]
Finds and fills value markers using given GET/POST parameters.
Parameters:
array &$gp Reference to the GET/POST parameters
Returns:
array The filled value markers
Definition at line 273 of file F3_MailformPlusPlus_StaticFuncs.php.
References reverse_htmlspecialchars().
Referenced by F3_MailformPlusPlus_StaticFuncs_testcase::test_getFilledValueMarkers().
static F3_MailformPlusPlus_StaticFuncs::getHostname () [static]
Returns the http path to the site
Returns:
string
Definition at line 191 of file F3_MailformPlusPlus_StaticFuncs.php.
Referenced by F3_MailformPlusPlus_StaticFuncs_testcase::test_getHostname().
static F3_MailformPlusPlus_StaticFuncs::getSubpart ($ content, $ marker) [static]
copied from class t3lib_parsehtml
Returns the first subpart encapsulated in the marker, $marker (possibly present in $content as a HTML comment)
Parameters:
string Content with subpart wrapped in fx. "###CONTENT_PART###" inside.
string Marker string, eg. "###CONTENT_PART###"
Returns:
string
Definition at line 97 of file F3_MailformPlusPlus_StaticFuncs.php.
Referenced by F3_MailformPlusPlus_Controller_Backend::generateCSVExportFieldsSelector(), F3_MailformPlusPlus_Controller_Backend::generateFormatsSelector(), F3_MailformPlusPlus_Controller_Backend::generatePDFExportFieldsSelector(), F3_MailformPlusPlus_Controller_Backend::getCalendarJS(), F3_MailformPlusPlus_Controller_Backend::getErrorMessage(), F3_MailformPlusPlus_Controller_Backend::getFilterSection(), F3_MailformPlusPlus_Controller_Backend::getFunctionArea(), F3_MailformPlusPlus_Controller_BackendClearLogs::getOverview(), F3_MailformPlusPlus_Controller_Backend::getSelectionBox(), F3_MailformPlusPlus_Controller_Backend::getSelectionJS(), F3_MailformPlusPlus_Controller_Backend::getTable(), and F3_MailformPlusPlus_Controller_Backend::showSingleView().
static F3_MailformPlusPlus_StaticFuncs::getTYPO3Root () [static]
Returns the absolute path to the TYPO3 root
Returns:
string
Definition at line 48 of file F3_MailformPlusPlus_StaticFuncs.php.
Referenced by F3_MailformPlusPlus_Controller_Default::getTempUploadFolder(), and F3_MailformPlusPlus_Controller_Default::processFiles().
static F3_MailformPlusPlus_StaticFuncs::pi_getFFvalue ($ T3FlexForm_array, $ fieldName, $ sheet = 'sDEF', $ lang = 'lDEF', $ value = 'vDEF') [static]
Return value from somewhere inside a FlexForm structure
Parameters:
array FlexForm data
string Field name to extract. Can be given like "test/el/2/test/el/field_templateObject" where each part will dig a level deeper in the FlexForm data.
string Sheet pointer, eg. "sDEF"
string Language pointer, eg. "lDEF"
string Value pointer, eg. "vDEF"
Returns:
string The content.
Definition at line 130 of file F3_MailformPlusPlus_StaticFuncs.php.
References $lang, and pi_getFFvalueFromSheetArray().
Referenced by F3_MailformPlusPlus_View_Default::fillFileMarkers(), F3_MailformPlusPlus_Validator_Default::loadConfig(), F3_MailformPlusPlus_Finisher_Redirect::loadConfig(), F3_MailformPlusPlus_Finisher_Mail::loadConfig(), F3_MailformPlusPlus_Finisher_Mail::parseEmailSettingsByType(), F3_MailformPlusPlus_Controller_Multistep::process(), F3_MailformPlusPlus_Controller_Default::process(), and F3_MailformPlusPlus_Controller_Default::validateConfig().
static F3_MailformPlusPlus_StaticFuncs::pi_getFFvalueFromSheetArray ($ sheetArray, $ fieldNameArr, $ value) [static, private]
Returns part of $sheetArray pointed to by the keys in $fieldNameArray
Parameters:
array Multidimensiona array, typically FlexForm contents
array Array where each value points to a key in the FlexForms content - the input array will have the value returned pointed to by these keys. All integer keys will not take their integer counterparts, but rather traverse the current position in the array an return element number X (whether this is right behavior is not settled yet...)
string Value for outermost key, typ. "vDEF" depending on language.
Returns:
mixed The value, typ. string. private
See also:
pi_getFFvalue()
Definition at line 147 of file F3_MailformPlusPlus_StaticFuncs.php.
Referenced by pi_getFFvalue().
static F3_MailformPlusPlus_StaticFuncs::prepareClassName ($ className) [static]
Adds needed prefix to class name if not set in TS
Returns:
string
Definition at line 60 of file F3_MailformPlusPlus_StaticFuncs.php.
Referenced by tx_MailformPlusPlus_Dispatcher::main(), F3_MailformPlusPlus_Finisher_Mail::parseEmailSettingsByType(), F3_MailformPlusPlus_Finisher_Confirmation::process(), F3_MailformPlusPlus_Controller_Multistep::process(), F3_MailformPlusPlus_Controller_Listing::process(), F3_MailformPlusPlus_Controller_Default::process(), and F3_MailformPlusPlus_Controller_Default::runClasses().
static F3_MailformPlusPlus_StaticFuncs::removeUnfilledMarkers ($ content) [static]
Removes unfilled markers from given template code.
Parameters:
string $content The template code
Returns:
string The template code without markers
Definition at line 389 of file F3_MailformPlusPlus_StaticFuncs.php.
Referenced by F3_MailformPlusPlus_Controller_Backend::getTable(), F3_MailformPlusPlus_View_Mail::render(), F3_MailformPlusPlus_View_Listing::render(), F3_MailformPlusPlus_View_Default::render(), F3_MailformPlusPlus_View_Confirmation::render(), and F3_MailformPlusPlus_StaticFuncs_testcase::test_removeUnfilledMarkers().
static F3_MailformPlusPlus_StaticFuncs::resolvePath ($ path) [static]
Substitutes EXT: with extension path in a file path
Parameters:
string The path
Returns:
string The resolved path
Definition at line 400 of file F3_MailformPlusPlus_StaticFuncs.php.
Referenced by F3_MailformPlusPlus_Finisher_Mail::getTemplate(), F3_MailformPlusPlus_Finisher_Mail::init(), F3_MailformPlusPlus_Finisher_Confirmation::process(), F3_MailformPlusPlus_Controller_Listing::process(), F3_MailformPlusPlus_Controller_Default::readTemplateFile(), and F3_MailformPlusPlus_StaticFuncs_testcase::test_resolvePath().
static F3_MailformPlusPlus_StaticFuncs::resolveRelPath ($ path) [static]
Substitutes EXT: with extension path in a file path and returns the relative path.
Parameters:
string The path
Returns:
string The resolved path
Definition at line 418 of file F3_MailformPlusPlus_StaticFuncs.php.
Referenced by F3_MailformPlusPlus_StaticFuncs_testcase::test_resolveRelPath().
static F3_MailformPlusPlus_StaticFuncs::resolveRelPathFromSiteRoot ($ path) [static]
Substitutes EXT: with extension path in a file path and returns the relative path from site root.
Parameters:
string The path
Returns:
string The resolved path
Definition at line 436 of file F3_MailformPlusPlus_StaticFuncs.php.
Referenced by F3_MailformPlusPlus_View_Default::readLangFile().
static F3_MailformPlusPlus_StaticFuncs::reverse_htmlspecialchars ($ mixed) [static]
I have no idea
Author:
Peter Luser <pl@typoheads.at>
Parameters:
string $mixed The value to process
Returns:
string The processed value
Definition at line 304 of file F3_MailformPlusPlus_StaticFuncs.php.
Referenced by getFilledValueMarkers().
static F3_MailformPlusPlus_StaticFuncs::sanitizePath ($ path) [static]
Ensures that a given path has a / as first and last character. This method only appends a / to the end of the path, if no filename is in path.
Examples:
uploads/temp --> /uploads/temp/ uploads/temp/file.ext --> /uploads/temp/file.ext
Parameters:
string $path
Returns:
string Sanitized path
Definition at line 207 of file F3_MailformPlusPlus_StaticFuncs.php.
Referenced by F3_MailformPlusPlus_Controller_Default::getTempUploadFolder(), F3_MailformPlusPlus_Finisher_StoreUploadedFiles::moveUploadedFiles(), and F3_MailformPlusPlus_StaticFuncs_testcase::test_sanitizePath().
static F3_MailformPlusPlus_StaticFuncs::substituteMarkerArray ($ content, $ markContentArray) [static]
copied from class tslib_content
Substitutes markers in given template string with data of marker array
Parameters:
string
array
Returns:
string
Definition at line 78 of file F3_MailformPlusPlus_StaticFuncs.php.
Referenced by F3_MailformPlusPlus_Controller_Backend::generateCSVExportFieldsSelector(), F3_MailformPlusPlus_Controller_Backend::generateFormatsSelector(), F3_MailformPlusPlus_Controller_Backend::generatePDFExportFieldsSelector(), F3_MailformPlusPlus_Controller_Backend::getErrorMessage(), F3_MailformPlusPlus_Controller_Backend::getFilterSection(), F3_MailformPlusPlus_Controller_Backend::getFunctionArea(), F3_MailformPlusPlus_Controller_BackendClearLogs::getOverview(), F3_MailformPlusPlus_Controller_Backend::getSelectionBox(), F3_MailformPlusPlus_Controller_Backend::getTable(), and F3_MailformPlusPlus_Controller_Backend::showSingleView().
static F3_MailformPlusPlus_StaticFuncs::throwException ($ key) [static]
Manages the exception throwing
Parameters:
string $key Key in language file
Returns:
void
Definition at line 344 of file F3_MailformPlusPlus_StaticFuncs.php.
References F3_MailformPlusPlus_Messages::getExceptionMessage().
Referenced by F3_MailformPlusPlus_Finisher_DB::init(), F3_MailformPlusPlus_Controller_Default::readTemplateFile(), F3_MailformPlusPlus_Finisher_DifferentDB::save(), F3_MailformPlusPlus_Finisher_Mail::validateConfig(), and F3_MailformPlusPlus_Controller_Default::validateConfig().
Member Data Documentation
F3_MailformPlusPlus_StaticFuncs::$cObj [static]
Definition at line 32 of file F3_MailformPlusPlus_StaticFuncs.php.
Referenced by F3_MailformPlusPlus_Controller_Default::__construct(), F3_MailformPlusPlus_AbstractView::__construct(), F3_MailformPlusPlus_AbstractValidator::__construct(), F3_MailformPlusPlus_AbstractPreProcessor::__construct(), F3_MailformPlusPlus_AbstractInterceptor::__construct(), F3_MailformPlusPlus_AbstractFinisher::__construct(), F3_MailformPlusPlus_AbstractErrorCheck::__construct(), and tx_MailformPlusPlus_Dispatcher::main().