mailformplusplus: F3_MailformPlusPlus_Interceptor_ParseValues Class Reference
F3_MailformPlusPlus_Interceptor_ParseValues Class Reference
Inherits F3_MailformPlusPlus_AbstractInterceptor.
Public Member Functions
process ($gp, $settings)
Protected Member Functions
parseFloats ($fields)
getFloat ($value)
Detailed Description
Definition at line 25 of file F3_MailformPlusPlus_Interceptor_ParseValues.php.
Member Function Documentation
F3_MailformPlusPlus_Interceptor_ParseValues::getFloat ($ value) [protected]
Parses the formated value as float. Needed for values like: x xxx,- / xx,xx / xx'xxx,xx / -xx.xxx,xx Caution: This pareses x.xxx.xxx to xxxxxxx (but xx.xx to xx.xx)
Returns:
float
Parameters:
string $value formated float
Definition at line 68 of file F3_MailformPlusPlus_Interceptor_ParseValues.php.
Referenced by parseFloats().
F3_MailformPlusPlus_Interceptor_ParseValues::parseFloats ($ fields) [protected]
parses the given field values from strings to floats
Returns:
void
Parameters:
array $fields
Definition at line 50 of file F3_MailformPlusPlus_Interceptor_ParseValues.php.
References getFloat().
Referenced by process().
F3_MailformPlusPlus_Interceptor_ParseValues::process ($ gp, $ settings)
The main method called by the controller
Parameters:
array $gp The GET/POST parameters
array $settings The defined TypoScript settings for the interceptor
Returns:
array The probably modified GET/POST parameters
Reimplemented from F3_MailformPlusPlus_AbstractInterceptor.
Definition at line 34 of file F3_MailformPlusPlus_Interceptor_ParseValues.php.
References F3_MailformPlusPlus_AbstractInterceptor::$gp, and parseFloats().