MailformPlusPlus: F3_MailformPlusPlus_Controller_BackendClearLogs Class Reference
F3_MailformPlusPlus_Controller_BackendClearLogs Class Reference
Inherits F3_MailformPlusPlus_AbstractController.
Public Member Functions
__construct (F3_GimmeFive_Component_Manager $componentManager, F3_MailformPlusPlus_Configuration $configuration)
process ()
Protected Member Functions
init ()
clearTables ($tablesArray)
getOverview ()
Protected Attributes
$componentManager
$configuration
Detailed Description
Definition at line 22 of file F3_MailformPlusPlus_Controller_BackendClearLogs.php.
Constructor & Destructor Documentation
F3_MailformPlusPlus_Controller_BackendClearLogs::__construct (F3_GimmeFive_Component_Manager $ componentManager, F3_MailformPlusPlus_Configuration $ configuration)
The constructor for a finisher setting the component manager and the configuration.
Parameters:
F3_GimmeFive_Component_Manager $componentManager
F3_MailformPlusPlus_Configuration $configuration
Returns:
void
Definition at line 49 of file F3_MailformPlusPlus_Controller_BackendClearLogs.php.
Member Function Documentation
F3_MailformPlusPlus_Controller_BackendClearLogs::clearTables ($ tablesArray) [protected]
Truncates tables.
Parameters:
array The names of the tables to truncate
Returns:
void
Definition at line 96 of file F3_MailformPlusPlus_Controller_BackendClearLogs.php.
Referenced by process().
F3_MailformPlusPlus_Controller_BackendClearLogs::getOverview () [protected]
Returns HTML code for an overview table showing all found tables and how many rows are in them.
$LANG
Returns:
string
Definition at line 108 of file F3_MailformPlusPlus_Controller_BackendClearLogs.php.
References F3_MailformPlusPlus_StaticFuncs::getSubpart(), and F3_MailformPlusPlus_StaticFuncs::substituteMarkerArray().
Referenced by process().
F3_MailformPlusPlus_Controller_BackendClearLogs::init () [protected]
init method to load translation data and set log table.
$LANG
Returns:
void
Definition at line 61 of file F3_MailformPlusPlus_Controller_BackendClearLogs.php.
Referenced by process().
F3_MailformPlusPlus_Controller_BackendClearLogs::process ()
Main method of the controller.
Returns:
string rendered view
Implements F3_MailformPlusPlus_ControllerInterface.
Definition at line 74 of file F3_MailformPlusPlus_Controller_BackendClearLogs.php.
References clearTables(), getOverview(), and init().
Member Data Documentation
F3_MailformPlusPlus_Controller_BackendClearLogs::$componentManager [protected]
Definition at line 31 of file F3_MailformPlusPlus_Controller_BackendClearLogs.php.
F3_MailformPlusPlus_Controller_BackendClearLogs::$configuration [protected]
Definition at line 39 of file F3_MailformPlusPlus_Controller_BackendClearLogs.php.