mailformplusplus: F3_MailformPlusPlus_Controller_Multistep Class Reference
F3_MailformPlusPlus_Controller_Multistep Class Reference
Inherits F3_MailformPlusPlus_Controller_Default.
Public Member Functions
process ()
Protected Member Functions
findCurrentStep ()
setViewSubpart (&$view, &$settings, $step)
mergeGPWithSession ()
storeGPinSession (&$settings)
Protected Attributes
$currentStep
Detailed Description
Definition at line 24 of file F3_MailformPlusPlus_Controller_Multistep.php.
Member Function Documentation
F3_MailformPlusPlus_Controller_Multistep::findCurrentStep () [protected]
Searches for current step and sets $this->currentStep according
Returns:
void
Author:
Reinhard Führicht <rf@typoheads.at>
Definition at line 327 of file F3_MailformPlusPlus_Controller_Multistep.php.
Referenced by process().
F3_MailformPlusPlus_Controller_Multistep::mergeGPWithSession () [protected]
Merges the current GET/POST parameters with the stored ones in SESSION
Returns:
void
Author:
Reinhard Führicht <rf@typoheads.at>
Definition at line 393 of file F3_MailformPlusPlus_Controller_Multistep.php.
Referenced by process().
F3_MailformPlusPlus_Controller_Multistep::process ()
Main method of the form handler.
Returns:
rendered view
Author:
Reinhard Führicht <rf@typoheads.at>
Reimplemented from F3_MailformPlusPlus_Controller_Default.
Definition at line 40 of file F3_MailformPlusPlus_Controller_Multistep.php.
References F3_MailformPlusPlus_Controller_Default::addSpecialJS(), F3_MailformPlusPlus_Controller_Default::clearSession(), F3_MailformPlusPlus_Controller_Default::clearTempFiles(), F3_MailformPlusPlus_StaticFuncs::debugArray(), F3_MailformPlusPlus_StaticFuncs::debugMessage(), findCurrentStep(), F3_MailformPlusPlus_AbstractController::getSettings(), F3_MailformPlusPlus_Controller_Default::isValid(), mergeGPWithSession(), F3_MailformPlusPlus_StaticFuncs::pi_getFFvalue(), F3_MailformPlusPlus_StaticFuncs::prepareClassName(), F3_MailformPlusPlus_Controller_Default::processFiles(), F3_MailformPlusPlus_Controller_Default::readTemplateFile(), F3_MailformPlusPlus_Controller_Default::runClasses(), F3_MailformPlusPlus_Controller_Default::setStyleSheet(), setViewSubpart(), storeGPinSession(), F3_MailformPlusPlus_Controller_Default::storeUserGPinSession(), and F3_MailformPlusPlus_Controller_Default::validateConfig().
F3_MailformPlusPlus_Controller_Multistep::setViewSubpart (&$ view, &$ settings, $ step) [protected]
Sets the template of the view.
Parameters:
F3_MailformPlusPlus_AbstractView &$view Reference to view object
array &$settings Reference to the settings array
integer $step The current step
Returns:
void
Author:
Reinhard Führicht <rf@typoheads.at>
Definition at line 362 of file F3_MailformPlusPlus_Controller_Multistep.php.
References F3_MailformPlusPlus_StaticFuncs::debugMessage().
Referenced by process().
F3_MailformPlusPlus_Controller_Multistep::storeGPinSession (&$ settings) [protected]
Stores the current GET/POST parameters in SESSION
Parameters:
array &$settings Reference to the settings array to get information about checkboxes and radiobuttons.
Returns:
void
Author:
Reinhard Führicht <rf@typoheads.at>
Definition at line 421 of file F3_MailformPlusPlus_Controller_Multistep.php.
Referenced by process().
Member Data Documentation
F3_MailformPlusPlus_Controller_Multistep::$currentStep [protected]
Definition at line 32 of file F3_MailformPlusPlus_Controller_Multistep.php.