mailformplusplus: F3_MailformPlusPlus_View_Mail Class Reference
F3_MailformPlusPlus_View_Mail Class Reference
Inherits F3_MailformPlusPlus_View_Default.
Public Member Functions
render ($gp, $errors)
Detailed Description
Definition at line 24 of file F3_MailformPlusPlus_View_Mail.php.
Member Function Documentation
F3_MailformPlusPlus_View_Mail::render ($ gp, $ errors)
Main method called by the controller.
Parameters:
array $gp The current GET/POST parameters
array $errors The errors occurred in validation
Returns:
string content
Reimplemented from F3_MailformPlusPlus_View_Default.
Definition at line 33 of file F3_MailformPlusPlus_View_Mail.php.
References F3_MailformPlusPlus_AbstractView::$gp, F3_MailformPlusPlus_View_Default::fillDefaultMarkers(), F3_MailformPlusPlus_View_Default::fillLangMarkers(), F3_MailformPlusPlus_View_Default::fillTypoScriptMarkers(), F3_MailformPlusPlus_View_Default::fillValueMarkers(), F3_MailformPlusPlus_View_Default::parseSettings(), F3_MailformPlusPlus_View_Default::readLangFile(), F3_MailformPlusPlus_StaticFuncs::removeUnfilledMarkers(), and F3_MailformPlusPlus_View_Default::substituteIssetSubparts().