mailformplusplus: F3_MailformPlusPlus_View_Confirmation Class Reference
F3_MailformPlusPlus_View_Confirmation Class Reference
Inherits F3_MailformPlusPlus_View_Default.
Public Member Functions
render ($gp, $errors)
Protected Member Functions
fillDefaultMarkers ()
Detailed Description
Definition at line 22 of file F3_MailformPlusPlus_View_Confirmation.php.
Member Function Documentation
F3_MailformPlusPlus_View_Confirmation::fillDefaultMarkers () [protected]
This function fills the default markers:
##PRINT_LINK### ##PDF_LINK### ##CSV_LINK###
Returns:
string Template with replaced markers
Reimplemented from F3_MailformPlusPlus_View_Default.
Definition at line 81 of file F3_MailformPlusPlus_View_Confirmation.php.
Referenced by render().
F3_MailformPlusPlus_View_Confirmation::render ($ gp, $ errors)
Main method called by the controller.
Parameters:
array $gp The current GET/POST parameters
array $errors The errors occurred in validation
Returns:
string content
Reimplemented from F3_MailformPlusPlus_View_Default.
Definition at line 31 of file F3_MailformPlusPlus_View_Confirmation.php.
References F3_MailformPlusPlus_AbstractView::$gp, fillDefaultMarkers(), F3_MailformPlusPlus_View_Default::fillLangMarkers(), F3_MailformPlusPlus_View_Default::fillTypoScriptMarkers(), F3_MailformPlusPlus_View_Default::fillValueMarkers(), F3_MailformPlusPlus_View_Default::parseSettings(), F3_MailformPlusPlus_View_Default::readLangFile(), F3_MailformPlusPlus_StaticFuncs::removeUnfilledMarkers(), and F3_MailformPlusPlus_StaticFuncs::substituteIssetSubparts().