mailformplusplus: DHTML_Calendar Class Reference
DHTML_Calendar Class Reference
Public Member Functions
DHTML_Calendar ($calendar_lib_path= '/calendar/', $lang= 'en', $theme= 'calendar-win2k-1', $stripped=true)
set_option ($name, $value)
load_files ()
get_load_files_code ()
_make_calendar ($other_options=array())
make_input_field ($cal_options=array(), $field_attributes=array())
_field_id ($id)
PRIVATE SECTION.
_trigger_id ($id)
_gen_id ()
_make_js_hash ($array)
_make_html_attr ($array)
Public Attributes
$calendar_lib_path
$calendar_file
$calendar_lang_file
$calendar_setup_file
$calendar_theme_file
$calendar_options
Detailed Description
Definition at line 24 of file calendar.php.
Member Function Documentation
DHTML_Calendar::_field_id ($ id)
PRIVATE SECTION.
Definition at line 100 of file calendar.php.
Referenced by make_input_field().
DHTML_Calendar::_gen_id ()
Definition at line 102 of file calendar.php.
Referenced by make_input_field().
DHTML_Calendar::_make_calendar ($ other_options = array())
Definition at line 75 of file calendar.php.
References _make_js_hash().
Referenced by make_input_field().
DHTML_Calendar::_make_html_attr ($ array)
Definition at line 118 of file calendar.php.
Referenced by make_input_field().
DHTML_Calendar::_make_js_hash ($ array)
Definition at line 104 of file calendar.php.
Referenced by _make_calendar().
DHTML_Calendar::_trigger_id ($ id)
Definition at line 101 of file calendar.php.
Referenced by make_input_field().
DHTML_Calendar::DHTML_Calendar ($ calendar_lib_path = '/calendar/', $ lang = 'en', $ theme = 'calendar-win2k-1', $ stripped = true)
Definition at line 33 of file calendar.php.
References $calendar_lib_path, and $lang.
DHTML_Calendar::get_load_files_code ()
Definition at line 59 of file calendar.php.
Referenced by load_files().
DHTML_Calendar::load_files ()
Definition at line 55 of file calendar.php.
References get_load_files_code().
DHTML_Calendar::make_input_field ($ cal_options = array(), $ field_attributes = array())
Definition at line 83 of file calendar.php.
References _field_id(), _gen_id(), _make_calendar(), _make_html_attr(), and _trigger_id().
DHTML_Calendar::set_option ($ name, $ value)
Definition at line 51 of file calendar.php.
Member Data Documentation
DHTML_Calendar::$calendar_file
Definition at line 27 of file calendar.php.
DHTML_Calendar::$calendar_lang_file
Definition at line 28 of file calendar.php.
DHTML_Calendar::$calendar_lib_path
Definition at line 25 of file calendar.php.
Referenced by DHTML_Calendar().
DHTML_Calendar::$calendar_options
Definition at line 31 of file calendar.php.
DHTML_Calendar::$calendar_setup_file
Definition at line 29 of file calendar.php.
DHTML_Calendar::$calendar_theme_file
Definition at line 30 of file calendar.php.