MailformPlusPlus: F3_MailformPlusPlus_View_Listing Class Reference
F3_MailformPlusPlus_View_Listing Class Reference
Inherits F3_MailformPlusPlus_AbstractView.
Public Member Functions
render ($gp, $errors)
Protected Member Functions
fillDefaultMarkers (&$markers, &$row=array())
getMapping ()
getValueMarkers (&$row)
Detailed Description
Definition at line 24 of file F3_MailformPlusPlus_View_Listing.php.
Member Function Documentation
F3_MailformPlusPlus_View_Listing::fillDefaultMarkers (&$ markers, &$ row = array()) [protected]
Fills the default markers: ##LINK2SHOW### ##DELETE### ##BACK_LINK###
Parameters:
array &$markers reference to the marker array
array &$row reference to the current record
Returns:
void
Definition at line 80 of file F3_MailformPlusPlus_View_Listing.php.
Referenced by render().
F3_MailformPlusPlus_View_Listing::getMapping () [protected]
Function to parse the db field <-> marker name settings in TypoScript
Returns:
array The parsed mapping
Definition at line 99 of file F3_MailformPlusPlus_View_Listing.php.
Referenced by render().
F3_MailformPlusPlus_View_Listing::getValueMarkers (&$ row) [protected]
Returns array with filled marker values of markers like ##value_[fieldname]###
Parameters:
&$row The current record
Returns:
array The marker array
Definition at line 117 of file F3_MailformPlusPlus_View_Listing.php.
Referenced by render().
F3_MailformPlusPlus_View_Listing::render ($ gp, $ errors)
Main method called by the controller.
Parameters:
array $gp The current GET/POST parameters
array $errors The errors occurred in validation
Returns:
string content
Reimplemented from F3_MailformPlusPlus_AbstractView.
Definition at line 33 of file F3_MailformPlusPlus_View_Listing.php.
References fillDefaultMarkers(), getMapping(), getValueMarkers(), and F3_MailformPlusPlus_StaticFuncs::removeUnfilledMarkers().