MailformPlusPlus: F3_MailformPlusPlus_Finisher_Confirmation Class Reference
F3_MailformPlusPlus_Finisher_Confirmation Class Reference
Inherits F3_MailformPlusPlus_AbstractFinisher.
Public Member Functions
process ()
Detailed Description
Definition at line 38 of file F3_MailformPlusPlus_Finisher_Confirmation.php.
Member Function Documentation
F3_MailformPlusPlus_Finisher_Confirmation::process ()
The main method called by the controller
Returns:
array The probably modified GET/POST parameters
Reimplemented from F3_MailformPlusPlus_AbstractFinisher.
Definition at line 45 of file F3_MailformPlusPlus_Finisher_Confirmation.php.
References F3_MailformPlusPlus_StaticFuncs::prepareClassName(), F3_MailformPlusPlus_StaticFuncs::resolvePath(), and F3_MailformPlusPlus_StaticFuncs::throwException().