mailformplusplus: F3_MailformPlusPlus_Controller_Listing Class Reference
F3_MailformPlusPlus_Controller_Listing Class Reference
Inherits F3_MailformPlusPlus_AbstractController.
Public Member Functions
__construct (F3_GimmeFive_Component_Manager $componentManager, F3_MailformPlusPlus_Configuration $configuration)
setTemplateFile ($template)
process ()
Protected Member Functions
getMapping (&$settings)
initializeController ($value='')
Protected Attributes
$componentManager
$configuration
$templateFile
$piVars
Detailed Description
Definition at line 57 of file F3_MailformPlusPlus_Controller_Listing.php.
Constructor & Destructor Documentation
F3_MailformPlusPlus_Controller_Listing::__construct (F3_GimmeFive_Component_Manager $ componentManager, F3_MailformPlusPlus_Configuration $ configuration)
The constructor setting the component manager and the configuration.
Author:
Reinhard Führicht <rf@typoheads.at>
Parameters:
F3_GimmeFive_Component_Manager $componentManager
F3_MailformPlusPlus_Configuration $configuration
Returns:
void
Definition at line 94 of file F3_MailformPlusPlus_Controller_Listing.php.
References initializeController().
Member Function Documentation
F3_MailformPlusPlus_Controller_Listing::getMapping (&$ settings) [protected]
Function to parse the db field <-> marker name settings in TypoScript
Parameters:
&$settings The settings
Returns:
array The parsed mapping
Author:
Reinhard Führicht <rf@typoheads.at>
Definition at line 211 of file F3_MailformPlusPlus_Controller_Listing.php.
Referenced by process().
F3_MailformPlusPlus_Controller_Listing::initializeController ($ value = '') [protected]
Possibly unnecessary
Returns:
void
Author:
Reinhard Führicht <rf@typoheads.at>
Definition at line 228 of file F3_MailformPlusPlus_Controller_Listing.php.
Referenced by __construct().
F3_MailformPlusPlus_Controller_Listing::process ()
Main method of the listing controller.
Author:
Reinhard Führicht <rf@typoheads.at>
Returns:
rendered view
Implements F3_MailformPlusPlus_ControllerInterface.
Definition at line 117 of file F3_MailformPlusPlus_Controller_Listing.php.
References $templateFile, getMapping(), and F3_MailformPlusPlus_StaticFuncs::resolvePath().
F3_MailformPlusPlus_Controller_Listing::setTemplateFile ($ template)
Sets the template file attribute to $template
Author:
Reinhard Führicht <rf@typoheads.at>
Parameters:
string $template
Returns:
void
Definition at line 107 of file F3_MailformPlusPlus_Controller_Listing.php.
Member Data Documentation
F3_MailformPlusPlus_Controller_Listing::$componentManager [protected]
Definition at line 65 of file F3_MailformPlusPlus_Controller_Listing.php.
F3_MailformPlusPlus_Controller_Listing::$configuration [protected]
Definition at line 73 of file F3_MailformPlusPlus_Controller_Listing.php.
F3_MailformPlusPlus_Controller_Listing::$piVars [protected]
Definition at line 84 of file F3_MailformPlusPlus_Controller_Listing.php.
F3_MailformPlusPlus_Controller_Listing::$templateFile [protected]
Definition at line 81 of file F3_MailformPlusPlus_Controller_Listing.php.
Referenced by process().