mailformplusplus: export2CSV Class Reference
export2CSV Class Reference
Public Member Functions
exportDb2CSV ($delimiter, $row_end)
create_csv_file_header ($data)
create_csv_file_row ($row)
create_csv_file ($data)
Public Attributes
$delimiter = ","
$row_end = "\n"
Detailed Description
Definition at line 11 of file csv.lib.php.
Member Function Documentation
export2CSV::create_csv_file ($ data)
Definition at line 55 of file csv.lib.php.
References create_csv_file_header(), and create_csv_file_row().
export2CSV::create_csv_file_header ($ data)
Definition at line 21 of file csv.lib.php.
Referenced by create_csv_file().
export2CSV::create_csv_file_row ($ row)
Definition at line 39 of file csv.lib.php.
Referenced by create_csv_file().
export2CSV::exportDb2CSV ($ delimiter, $ row_end)
Definition at line 16 of file csv.lib.php.
References $delimiter, and $row_end.
Member Data Documentation
export2CSV::$delimiter = ","
Definition at line 13 of file csv.lib.php.
Referenced by exportDb2CSV().
export2CSV::$row_end = "\n"
Definition at line 14 of file csv.lib.php.
Referenced by exportDb2CSV().