MailformPlusPlus: F3_MailformPlusPlus_Interceptor_IPBlocking Class Reference
F3_MailformPlusPlus_Interceptor_IPBlocking Class Reference
Inherits F3_MailformPlusPlus_AbstractInterceptor.
Public Member Functions
process ($gp, $settings)
Protected Attributes
$reportTable = 'tx_mailformplusplus_reportlog'
$logTable = 'tx_mailformplusplus_log'
Private Member Functions
check ($value, $unit, $maxValue, $addIPToWhere=false)
doRedirect ($emailRedirect)
sendReport ($type, &$rows)
getTimestamp ($value, $unit)
Detailed Description
Definition at line 51 of file F3_MailformPlusPlus_Interceptor_IPBlocking.php.
Member Function Documentation
F3_MailformPlusPlus_Interceptor_IPBlocking::check ($ value, $ unit, $ maxValue, $ addIPToWhere = false) [private]
Checks if the form got submitted too often and throws Exception if true.
Parameters:
int Timebase value
string Timebase unit (seconds|minutes|hours|days)
int maximum amount of submissions in given time base.
boolean add IP address to where clause
Returns:
void
Definition at line 105 of file F3_MailformPlusPlus_Interceptor_IPBlocking.php.
References getTimestamp().
Referenced by process().
F3_MailformPlusPlus_Interceptor_IPBlocking::doRedirect ($ emailRedirect) [private]
Redirects to given page id or url
Parameters:
mixed $emailRedirect
Returns:
void
Definition at line 168 of file F3_MailformPlusPlus_Interceptor_IPBlocking.php.
F3_MailformPlusPlus_Interceptor_IPBlocking::getTimestamp ($ value, $ unit) [private]
Parses given value and unit and creates a timestamp now-timebase.
Parameters:
int Timebase value
string Timebase unit (seconds|minutes|hours|days)
Returns:
long The timestamp
Definition at line 279 of file F3_MailformPlusPlus_Interceptor_IPBlocking.php.
Referenced by check().
F3_MailformPlusPlus_Interceptor_IPBlocking::process ($ gp, $ settings)
The main method called by the controller
Parameters:
array $gp The GET/POST parameters
array $settings The defined TypoScript settings for the finisher
Returns:
array The probably modified GET/POST parameters
Reimplemented from F3_MailformPlusPlus_AbstractInterceptor.
Definition at line 76 of file F3_MailformPlusPlus_Interceptor_IPBlocking.php.
References F3_MailformPlusPlus_AbstractInterceptor::$gp, and check().
F3_MailformPlusPlus_Interceptor_IPBlocking::sendReport ($ type, &$ rows) [private]
Sends a report mail to recipients set in TypoScript.
Parameters:
string (ip|global) Defines the message sent
array The select rows of log table
Returns:
void
Definition at line 203 of file F3_MailformPlusPlus_Interceptor_IPBlocking.php.
References F3_MailformPlusPlus_StaticFuncs::debugMessage().
Member Data Documentation
F3_MailformPlusPlus_Interceptor_IPBlocking::$logTable = 'tx_mailformplusplus_log' [protected]
Definition at line 67 of file F3_MailformPlusPlus_Interceptor_IPBlocking.php.
F3_MailformPlusPlus_Interceptor_IPBlocking::$reportTable = 'tx_mailformplusplus_reportlog' [protected]
Definition at line 59 of file F3_MailformPlusPlus_Interceptor_IPBlocking.php.