mailformplusplus: F3_MailformPlusPlus_Finisher_DB Class Reference
F3_MailformPlusPlus_Finisher_DB Class Reference
Inherits F3_MailformPlusPlus_AbstractFinisher.
Inherited by F3_MailformPlusPlus_Finisher_DifferentDB.
Public Member Functions
process ()
Protected Member Functions
parseCondition ($condition)
save (&$queryFields)
init ()
parseFields ()
getFileList ($fieldname)
Protected Attributes
$table
$key
$doUpdate
Detailed Description
Definition at line 60 of file F3_MailformPlusPlus_Finisher_DB.php.
Member Function Documentation
F3_MailformPlusPlus_Finisher_DB::getFileList ($ fieldname) [protected]
returns a list of uploaded files from given field.
Returns:
string list of filenames
Parameters:
string $fieldname
Definition at line 284 of file F3_MailformPlusPlus_Finisher_DB.php.
Referenced by parseFields().
F3_MailformPlusPlus_Finisher_DB::init () [protected]
Inits the finisher mapping settings values to internal attributes.
Returns:
void
Reimplemented in F3_MailformPlusPlus_Finisher_DifferentDB.
Definition at line 180 of file F3_MailformPlusPlus_Finisher_DB.php.
References F3_MailformPlusPlus_StaticFuncs::throwException().
Referenced by process().
F3_MailformPlusPlus_Finisher_DB::parseCondition ($ condition) [protected]
Parses condition statement given by the typoscript configuration. Replaces field with real content for a proper PHP eval().
Author:
Fabien Udriot <fabien.udriot@ecodev.ch>
Parameters:
string $condition: the condition given by the typoscript configuration.
Returns:
string $condition: the condition formated for evaluation.
Definition at line 125 of file F3_MailformPlusPlus_Finisher_DB.php.
Referenced by process().
F3_MailformPlusPlus_Finisher_DB::parseFields () [protected]
Parses mapping settings and builds an array holding the query fields information.
Returns:
array The query fields
Definition at line 211 of file F3_MailformPlusPlus_Finisher_DB.php.
References getFileList().
Referenced by process().
F3_MailformPlusPlus_Finisher_DB::process ()
The main method called by the controller
Returns:
array The probably modified GET/POST parameters
Reimplemented from F3_MailformPlusPlus_AbstractFinisher.
Definition at line 91 of file F3_MailformPlusPlus_Finisher_DB.php.
References F3_MailformPlusPlus_StaticFuncs::debugMessage(), init(), parseCondition(), parseFields(), and save().
F3_MailformPlusPlus_Finisher_DB::save (&$ queryFields) [protected]
Method to query the database making an insert or update statement using the given fields.
Parameters:
array &$queryFields Array holding the query fields
Returns:
void
Reimplemented in F3_MailformPlusPlus_Finisher_DifferentDB.
Definition at line 147 of file F3_MailformPlusPlus_Finisher_DB.php.
References F3_MailformPlusPlus_StaticFuncs::debugMessage().
Referenced by process().
Member Data Documentation
F3_MailformPlusPlus_Finisher_DB::$doUpdate [protected]
Definition at line 84 of file F3_MailformPlusPlus_Finisher_DB.php.
F3_MailformPlusPlus_Finisher_DB::$key [protected]
Definition at line 76 of file F3_MailformPlusPlus_Finisher_DB.php.
F3_MailformPlusPlus_Finisher_DB::$table [protected]
Definition at line 68 of file F3_MailformPlusPlus_Finisher_DB.php.