mailformplusplus: F3_MailformPlusPlus_View_Default Class Reference
F3_MailformPlusPlus_View_Default Class Reference
Inherits F3_MailformPlusPlus_AbstractView.
Inherited by F3_MailformPlusPlus_View_Confirmation, F3_MailformPlusPlus_View_Mail, and F3_MailformPlusPlus_View_Multistep.
Public Member Functions
removeUploadedFile ($fieldname, $filename)
render ($gp, $errors)
Protected Member Functions
readLangFile ()
markersCountAsSet ($conditionValue)
substituteIssetSubparts ()
storeStartEndBlock ()
fillStartEndBlock ()
parseSettings ()
fillSelectedMarkers ()
fillDefaultMarkers ()
fillCaptchaMarkers (&$markers)
fillFEUserMarkers (&$markers)
fillFileMarkers (&$markers)
fillIsErrorMarkers (&$errors)
fillErrorMarkers (&$errors)
fillTypoScriptMarkers ()
fillValueMarkers ()
fillLangMarkers ()
Detailed Description
Definition at line 24 of file F3_MailformPlusPlus_View_Default.php.
Member Function Documentation
F3_MailformPlusPlus_View_Default::fillCaptchaMarkers (&$ markers) [protected]
Fills the markers for the supported captcha extensions.
Parameters:
array &$markers Reference to the markers array
Returns:
void
Definition at line 347 of file F3_MailformPlusPlus_View_Default.php.
References F3_MailformPlusPlus_AbstractView::$langFile, and MathGuard::returnQuestion().
Referenced by fillDefaultMarkers().
F3_MailformPlusPlus_View_Default::fillDefaultMarkers () [protected]
Substitutes default markers in $this->template.
Returns:
void
Reimplemented in F3_MailformPlusPlus_View_Confirmation, and F3_MailformPlusPlus_View_Multistep.
Definition at line 320 of file F3_MailformPlusPlus_View_Default.php.
References fillCaptchaMarkers(), fillFEUserMarkers(), fillFileMarkers(), and parseSettings().
Referenced by F3_MailformPlusPlus_View_Mail::render(), and render().
F3_MailformPlusPlus_View_Default::fillErrorMarkers (&$ errors) [protected]
Substitutes markers ##error_[fieldname]### ##ERROR### in $this->template
Returns:
void
Definition at line 630 of file F3_MailformPlusPlus_View_Default.php.
Referenced by render().
F3_MailformPlusPlus_View_Default::fillFEUserMarkers (&$ markers) [protected]
Fills the markers ##FEUSER_[property]### with the data from $GLOBALS["TSFE"]->fe_user->user.
Parameters:
array &$markers Reference to the markers array
Returns:
void
Definition at line 395 of file F3_MailformPlusPlus_View_Default.php.
Referenced by fillDefaultMarkers().
F3_MailformPlusPlus_View_Default::fillFileMarkers (&$ markers) [protected]
Fills the file specific markers:
###[fieldname]_minSize### ###[fieldname]_maxSize### ###[fieldname]_allowedTypes### ###[fieldname]_maxCount### ###[fieldname]_fileCount### ###[fieldname]_remainingCount###
###[fieldname]_uploadedFiles### ##total_uploadedFiles###
Parameters:
array &$markers Reference to the markers array
Returns:
void
Definition at line 422 of file F3_MailformPlusPlus_View_Default.php.
References parseSettings(), and F3_MailformPlusPlus_StaticFuncs::pi_getFFvalue().
Referenced by fillDefaultMarkers(), and removeUploadedFile().
F3_MailformPlusPlus_View_Default::fillIsErrorMarkers (&$ errors) [protected]
Substitutes markers ##is_error_[fieldname]### ##is_error### in $this->template
Returns:
void
Definition at line 587 of file F3_MailformPlusPlus_View_Default.php.
Referenced by render().
F3_MailformPlusPlus_View_Default::fillLangMarkers () [protected]
Substitutes markers ##LLL:[languageKey]### in $this->template
Returns:
void
Definition at line 785 of file F3_MailformPlusPlus_View_Default.php.
Referenced by F3_MailformPlusPlus_View_Mail::render(), render(), and F3_MailformPlusPlus_View_Confirmation::render().
F3_MailformPlusPlus_View_Default::fillSelectedMarkers () [protected]
Substitutes markers ##selected_[fieldname]_[value]### ##checked_[fieldname]_[value]### in $this->template
Returns:
void
Definition at line 298 of file F3_MailformPlusPlus_View_Default.php.
Referenced by render().
F3_MailformPlusPlus_View_Default::fillStartEndBlock () [protected]
Fills the markers ##FORM_STARTBLOCK### and ##FORM_ENDBLOCK### with the stored values from $_SESSION.
Returns:
void
Definition at line 260 of file F3_MailformPlusPlus_View_Default.php.
Referenced by render().
F3_MailformPlusPlus_View_Default::fillTypoScriptMarkers () [protected]
Substitutes markers defined in TypoScript in $this->template
Returns:
void
Definition at line 720 of file F3_MailformPlusPlus_View_Default.php.
Referenced by F3_MailformPlusPlus_View_Mail::render(), render(), and F3_MailformPlusPlus_View_Confirmation::render().
F3_MailformPlusPlus_View_Default::fillValueMarkers () [protected]
Substitutes markers ##value_[fieldname]### ##VALUE_[FIELDNAME]### ###[fieldname]### ###[FIELDNAME]### in $this->template
Returns:
void
Definition at line 747 of file F3_MailformPlusPlus_View_Default.php.
Referenced by F3_MailformPlusPlus_View_Mail::render(), render(), and F3_MailformPlusPlus_View_Confirmation::render().
F3_MailformPlusPlus_View_Default::markersCountAsSet ($ conditionValue) [protected]
Helper method used by substituteIssetSubparts()
See also:
F3_MailformPlusPlus_StaticFuncs::substituteIssetSubparts()
Author:
Stephan Bauer <stephan_bauer(at)gmx.de>
Returns:
boolean
Definition at line 165 of file F3_MailformPlusPlus_View_Default.php.
References F3_MailformPlusPlus_StaticFuncs::debugMessage().
Referenced by substituteIssetSubparts().
F3_MailformPlusPlus_View_Default::parseSettings () [protected]
Returns the global TypoScript settings of MailformPlusPlus
Returns:
array The settings
Reimplemented in F3_MailformPlusPlus_View_Multistep.
Definition at line 275 of file F3_MailformPlusPlus_View_Default.php.
Referenced by fillDefaultMarkers(), fillFileMarkers(), F3_MailformPlusPlus_View_Mail::render(), render(), and F3_MailformPlusPlus_View_Confirmation::render().
F3_MailformPlusPlus_View_Default::readLangFile () [protected]
Reads the translation file entered in TS setup.
Returns:
void
Definition at line 150 of file F3_MailformPlusPlus_View_Default.php.
References F3_MailformPlusPlus_StaticFuncs::resolveRelPathFromSiteRoot().
Referenced by F3_MailformPlusPlus_View_Mail::render(), render(), and F3_MailformPlusPlus_View_Confirmation::render().
F3_MailformPlusPlus_View_Default::removeUploadedFile ($ fieldname, $ filename)
Removes an uploaded file from $_SESSION. This method is called via an AJAX request.
Parameters:
string $fieldname The field holding the file to delete
string $filename The file to delete
Returns:
void
Definition at line 33 of file F3_MailformPlusPlus_View_Default.php.
References fillFileMarkers().
F3_MailformPlusPlus_View_Default::render ($ gp, $ errors)
Main method called by the controller.
Parameters:
array $gp The current GET/POST parameters
array $errors The errors occurred in validation
Returns:
string content
Reimplemented from F3_MailformPlusPlus_AbstractView.
Reimplemented in F3_MailformPlusPlus_View_Confirmation, and F3_MailformPlusPlus_View_Mail.
Definition at line 82 of file F3_MailformPlusPlus_View_Default.php.
References F3_MailformPlusPlus_AbstractView::$gp, fillDefaultMarkers(), fillErrorMarkers(), fillIsErrorMarkers(), fillLangMarkers(), fillSelectedMarkers(), fillStartEndBlock(), fillTypoScriptMarkers(), fillValueMarkers(), parseSettings(), readLangFile(), F3_MailformPlusPlus_StaticFuncs::removeUnfilledMarkers(), storeStartEndBlock(), and substituteIssetSubparts().
F3_MailformPlusPlus_View_Default::storeStartEndBlock () [protected]
Copies the subparts ##FORM_STARTBLOCK### and ##FORM_ENDBLOCK### and stored them in $_SESSION. This is needed to replace the markers ##FORM_STARTBLOCK### and ##FORM_ENDBLOCK### in the next steps.
Returns:
void
Definition at line 245 of file F3_MailformPlusPlus_View_Default.php.
Referenced by render().
F3_MailformPlusPlus_View_Default::substituteIssetSubparts () [protected]
Use or remove subparts with ISSET_[fieldname] patterns (thx to Stephan Bauer <stephan_bauer(at)gmx.de>)
Author:
Stephan Bauer <stephan_bauer(at)gmx.de>
Returns:
string substituted HTML content
Definition at line 202 of file F3_MailformPlusPlus_View_Default.php.
References markersCountAsSet().
Referenced by F3_MailformPlusPlus_View_Mail::render(), render(), and F3_MailformPlusPlus_View_Confirmation::render().