MailformPlusPlus: search.php File Reference
search.php File Reference
Functions
search_results ()
matches_text ($num)
report_matches ()
end_form ($value)
readInt ($file)
readString ($file)
readHeader ($file)
computeIndex ($word)
search ($file, $word, &$statsList)
combine_results ($results, &$docs)
filter_results ($docs, &$requiredWords, &$forbiddenWords)
compare_rank ($a, $b)
sort_results ($docs, &$sorted)
report_results (&$docs)
main ()
Function Documentation
combine_results ($ results, &$ docs)
Definition at line 194 of file search.php.
Referenced by main().
compare_rank ($ a, $ b)
Definition at line 264 of file search.php.
computeIndex ($ word)
Definition at line 72 of file search.php.
Referenced by search().
end_form ($ value)
Definition at line 46 of file search.php.
Referenced by main().
filter_results ($ docs, &$ requiredWords, &$ forbiddenWords)
Definition at line 224 of file search.php.
Referenced by main().
main ()
Definition at line 322 of file search.php.
References combine_results(), end_form(), filter_results(), readHeader(), report_results(), search(), and sort_results().
matches_text ($ num)
Definition at line 26 of file search.php.
readHeader ($ file)
Definition at line 65 of file search.php.
Referenced by main().
readInt ($ file)
Definition at line 51 of file search.php.
Referenced by search().
readString ($ file)
Definition at line 58 of file search.php.
Referenced by search().
report_matches ()
Definition at line 42 of file search.php.
report_results (&$ docs)
Definition at line 280 of file search.php.
Referenced by main().
search ($ file, $ word, &$ statsList)
Definition at line 96 of file search.php.
References computeIndex(), readInt(), and readString().
Referenced by main().
search_results ()
Definition at line 21 of file search.php.
sort_results ($ docs, &$ sorted)
Definition at line 273 of file search.php.
Referenced by main().