mailformplusplus: MathGuard Class Reference
MathGuard Class Reference
Public Member Functions
produceOutput ($question, $color, $prime)
decToBin ($dec)
renderExpression ($a, $b)
encode ($input, $prime)
generateCode ($a, $b, $prime)
checkResult ($mathguard_answer, $mathguard_code, $prime=37)
insertQuestion ($prime=37)
returnQuestion ($question=QUESTION, $color=COLOR, $prime=37)
Detailed Description
Definition at line 19 of file ClassMathGuard.php.
Member Function Documentation
MathGuard::checkResult ($ mathguard_answer, $ mathguard_code, $ prime = 37)
This function checks whether the answer and generated security code match
Parameters:
$mathguard_answer answer the user has entered
$mathguard_code hashcode the mathguard has generated
Definition at line 195 of file ClassMathGuard.php.
References encode().
Referenced by F3_MailformPlusPlus_Validator_Default::validateMathGuard().
MathGuard::decToBin ($ dec)
function that converts the decimal number to line of 3 random characters
Parameters:
$dec decimal number that is being converted to line of 3 random characters
Definition at line 48 of file ClassMathGuard.php.
Referenced by renderExpression().
MathGuard::encode ($ input, $ prime)
A main hashing function: concat of user's answer, hour and the additional prime number (default 37)
Definition at line 177 of file ClassMathGuard.php.
Referenced by checkResult(), and generateCode().
MathGuard::generateCode ($ a, $ b, $ prime)
This function generates the hash code from the two numbers
Parameters:
$a first number
$b second sumber
$prime additional number to encode with
Definition at line 186 of file ClassMathGuard.php.
References encode().
Referenced by produceOutput().
MathGuard::insertQuestion ($ prime = 37)
this function inserts the two math term into your form, the parameter is optional
Definition at line 208 of file ClassMathGuard.php.
References produceOutput().
MathGuard::produceOutput ($ question, $ color, $ prime)
you can also modify $output to your needs
Definition at line 22 of file ClassMathGuard.php.
References generateCode(), and renderExpression().
Referenced by insertQuestion(), and returnQuestion().
MathGuard::renderExpression ($ a, $ b)
function that renders a final 3x5 matrix consisting of random characters
Parameters:
$a random number a that renders to the 3x5 matrix consisting of random characters
$b random number b that renders to the 3x5 matrix consisting of random characters
Definition at line 74 of file ClassMathGuard.php.
References decToBin().
Referenced by produceOutput().
MathGuard::returnQuestion ($ question = QUESTION, $ color = COLOR, $ prime = 37)
this function returns math expression into your form, the parameter is optional quite simmilar to insertQuestion, but returns the output as a text instead of echoing
Definition at line 219 of file ClassMathGuard.php.
References produceOutput().
Referenced by F3_MailformPlusPlus_View_Default::fillCaptchaMarkers().