mailformplusplus: FPDF Class Reference
FPDF Class Reference
Public Member Functions
FPDF ($orientation='P', $unit='mm', $format='A4')
SetMargins ($left, $top, $right=null)
SetLeftMargin ($margin)
SetTopMargin ($margin)
SetRightMargin ($margin)
SetAutoPageBreak ($auto, $margin=0)
SetDisplayMode ($zoom, $layout='continuous')
SetCompression ($compress)
SetTitle ($title, $isUTF8=false)
SetSubject ($subject, $isUTF8=false)
SetAuthor ($author, $isUTF8=false)
SetKeywords ($keywords, $isUTF8=false)
SetCreator ($creator, $isUTF8=false)
AliasNbPages ($alias='{nb}')
Error ($msg)
Open ()
Close ()
AddPage ($orientation='', $format='')
Header ()
Footer ()
PageNo ()
SetDrawColor ($r, $g=null, $b=null)
SetFillColor ($r, $g=null, $b=null)
SetTextColor ($r, $g=null, $b=null)
GetStringWidth ($s)
SetLineWidth ($width)
Line ($x1, $y1, $x2, $y2)
Rect ($x, $y, $w, $h, $style='')
AddFont ($family, $style='', $file='')
SetFont ($family, $style='', $size=0)
SetFontSize ($size)
AddLink ()
SetLink ($link, $y=0, $page=-1)
Link ($x, $y, $w, $h, $link)
Text ($x, $y, $txt)
AcceptPageBreak ()
Cell ($w, $h=0, $txt='', $border=0, $ln=0, $align='', $fill=false, $link='')
MultiCell ($w, $h, $txt, $border=0, $align='J', $fill=false)
Write ($h, $txt, $link='')
Ln ($h=null)
Image ($file, $x=null, $y=null, $w=0, $h=0, $type='', $link='')
GetX ()
SetX ($x)
GetY ()
SetY ($y)
SetXY ($x, $y)
Output ($name='', $dest='')
_dochecks ()
_getpageformat ($format)
_getfontpath ()
_beginpage ($orientation, $format)
_endpage ()
_escape ($s)
_textstring ($s)
_UTF8toUTF16 ($s)
_dounderline ($x, $y, $txt)
_parsejpg ($file)
_parsepng ($file)
_readstream ($f, $n)
_readint ($f)
_parsegif ($file)
_newobj ()
_putstream ($s)
_out ($s)
_putpages ()
_putfonts ()
_putimages ()
_putxobjectdict ()
_putresourcedict ()
_putresources ()
_putinfo ()
_putcatalog ()
_putheader ()
_puttrailer ()
_enddoc ()
Public Attributes
$page
$n
$offsets
$buffer
$pages
$state
$compress
$k
$DefOrientation
$CurOrientation
$PageFormats
$DefPageFormat
$CurPageFormat
$PageSizes
$wPt
$hPt
$w
$h
$lMargin
$tMargin
$rMargin
$bMargin
$cMargin
$x
$y
$lasth
$LineWidth
$CoreFonts
$fonts
$FontFiles
$diffs
$FontFamily
$FontStyle
$underline
$CurrentFont
$FontSizePt
$FontSize
$DrawColor
$FillColor
$TextColor
$ColorFlag
$ws
$images
$PageLinks
$links
$AutoPageBreak
$PageBreakTrigger
$InHeader
$InFooter
$ZoomMode
$LayoutMode
$title
$subject
$author
$keywords
$creator
$AliasNbPages
$PDFVersion
Detailed Description
Definition at line 23 of file fpdf.php.
Member Function Documentation
FPDF::_beginpage ($ orientation, $ format)
Definition at line 1104 of file fpdf.php.
References _getpageformat().
Referenced by AddPage().
FPDF::_dochecks ()
Definition at line 1075 of file fpdf.php.
References Error().
Referenced by FPDF().
FPDF::_dounderline ($ x, $ y, $ txt)
Definition at line 1201 of file fpdf.php.
References $w, $x, $y, and GetStringWidth().
FPDF::_enddoc ()
Definition at line 1699 of file fpdf.php.
Referenced by Close().
FPDF::_endpage ()
Definition at line 1147 of file fpdf.php.
Referenced by AddPage(), and Close().
FPDF::_escape ($ s)
Definition at line 1152 of file fpdf.php.
Referenced by Text().
FPDF::_getfontpath ()
Definition at line 1097 of file fpdf.php.
Referenced by AddFont(), and SetFont().
FPDF::_getpageformat ($ format)
Definition at line 1088 of file fpdf.php.
References Error().
Referenced by _beginpage(), and FPDF().
FPDF::_newobj ()
Definition at line 1363 of file fpdf.php.
FPDF::_out ($ s)
Definition at line 1378 of file fpdf.php.
Referenced by AddPage(), Cell(), Image(), Line(), MultiCell(), Rect(), SetDrawColor(), SetFillColor(), SetFont(), SetFontSize(), SetLineWidth(), and Text().
FPDF::_parsegif ($ file)
Definition at line 1341 of file fpdf.php.
FPDF::_parsejpg ($ file)
Definition at line 1210 of file fpdf.php.
References Error().
FPDF::_parsepng ($ file)
Definition at line 1234 of file fpdf.php.
References $h, $n, $w, _readint(), _readstream(), and Error().
FPDF::_putcatalog ()
Definition at line 1667 of file fpdf.php.
FPDF::_putfonts ()
Definition at line 1458 of file fpdf.php.
FPDF::_putheader ()
Definition at line 1687 of file fpdf.php.
FPDF::_putimages ()
Definition at line 1572 of file fpdf.php.
FPDF::_putinfo ()
Definition at line 1651 of file fpdf.php.
FPDF::_putpages ()
Definition at line 1387 of file fpdf.php.
FPDF::_putresourcedict ()
Definition at line 1626 of file fpdf.php.
FPDF::_putresources ()
Definition at line 1638 of file fpdf.php.
FPDF::_putstream ($ s)
Definition at line 1371 of file fpdf.php.
FPDF::_puttrailer ()
Definition at line 1692 of file fpdf.php.
FPDF::_putxobjectdict ()
Definition at line 1620 of file fpdf.php.
FPDF::_readint ($ f)
Definition at line 1334 of file fpdf.php.
Referenced by _parsepng().
FPDF::_readstream ($ f, $ n)
Definition at line 1317 of file fpdf.php.
Referenced by _parsepng().
FPDF::_textstring ($ s)
Definition at line 1162 of file fpdf.php.
FPDF::_UTF8toUTF16 ($ s)
Definition at line 1168 of file fpdf.php.
Referenced by SetAuthor(), SetCreator(), SetKeywords(), SetSubject(), and SetTitle().
FPDF::AcceptPageBreak ()
Definition at line 620 of file fpdf.php.
Referenced by Cell(), and Image().
FPDF::AddFont ($ family, $ style = '', $ file = '')
Definition at line 464 of file fpdf.php.
References _getfontpath(), and Error().
FPDF::AddLink ()
Definition at line 585 of file fpdf.php.
References $n.
FPDF::AddPage ($ orientation = '', $ format = '')
Definition at line 308 of file fpdf.php.
References _beginpage(), _endpage(), _out(), Footer(), Header(), Open(), and SetFont().
Referenced by Cell(), Close(), and Image().
FPDF::AliasNbPages ()
Definition at line 273 of file fpdf.php.
FPDF::Cell ($ w, $ h = 0, $ txt = '', $ border = 0, $ ln = 0, $ align = '', $ fill = false, $ link = '')
Definition at line 626 of file fpdf.php.
References $h, $k, $w, $ws, $x, $y, _out(), AcceptPageBreak(), AddPage(), GetStringWidth(), and Link().
Referenced by MultiCell(), and Write().
FPDF::Close ()
Definition at line 291 of file fpdf.php.
References _enddoc(), _endpage(), AddPage(), and Footer().
Referenced by Output().
FPDF::Error ($ msg)
Definition at line 279 of file fpdf.php.
Referenced by _dochecks(), _getpageformat(), _parsejpg(), _parsepng(), AddFont(), FPDF(), Image(), Output(), SetDisplayMode(), and SetFont().
FPDF::Footer ()
Definition at line 382 of file fpdf.php.
Referenced by AddPage(), and Close().
FPDF::FPDF ($ orientation = 'P', $ unit = 'mm', $ format = 'A4')
Definition at line 86 of file fpdf.php.
References _dochecks(), _getpageformat(), Error(), SetAutoPageBreak(), SetCompression(), SetDisplayMode(), and SetMargins().
FPDF::GetStringWidth ($ s)
Definition at line 426 of file fpdf.php.
References $w.
Referenced by _dounderline(), and Cell().
FPDF::GetX ()
Definition at line 965 of file fpdf.php.
FPDF::GetY ()
Definition at line 980 of file fpdf.php.
FPDF::Header ()
Definition at line 377 of file fpdf.php.
Referenced by AddPage().
FPDF::Image ($ file, $ x = null, $ y = null, $ w = 0, $ h = 0, $ type = '', $ link = '')
Definition at line 909 of file fpdf.php.
References $h, $w, $x, $y, _out(), AcceptPageBreak(), AddPage(), Error(), and Link().
FPDF::Line ($ x1, $ y1, $ x2, $ y2)
Definition at line 446 of file fpdf.php.
References _out().
FPDF::Link ($ x, $ y, $ w, $ h, $ link)
Definition at line 603 of file fpdf.php.
References $h, $w, $x, and $y.
Referenced by Cell(), and Image().
FPDF::Ln ($ h = null)
Definition at line 899 of file fpdf.php.
References $h.
FPDF::MultiCell ($ w, $ h, $ txt, $ border = 0, $ align = 'J', $ fill = false)
Definition at line 705 of file fpdf.php.
References $h, $w, _out(), and Cell().
FPDF::Open ()
Definition at line 285 of file fpdf.php.
Referenced by AddPage().
FPDF::Output ($ name = '', $ dest = '')
Definition at line 1003 of file fpdf.php.
References Close(), and Error().
FPDF::PageNo ()
Definition at line 387 of file fpdf.php.
FPDF::Rect ($ x, $ y, $ w, $ h, $ style = '')
Definition at line 452 of file fpdf.php.
References $h, $w, $x, $y, and _out().
FPDF::SetAuthor ($ author, $ isUTF8 = false)
Definition at line 249 of file fpdf.php.
References $author, and _UTF8toUTF16().
FPDF::SetAutoPageBreak ($ auto, $ margin = 0)
Definition at line 203 of file fpdf.php.
Referenced by FPDF().
FPDF::SetCompression ($ compress)
Definition at line 224 of file fpdf.php.
References $compress.
Referenced by FPDF().
FPDF::SetCreator ($ creator, $ isUTF8 = false)
Definition at line 265 of file fpdf.php.
References $creator, and _UTF8toUTF16().
FPDF::SetDisplayMode ($ zoom, $ layout = 'continuous')
Definition at line 211 of file fpdf.php.
References Error().
Referenced by FPDF().
FPDF::SetDrawColor ($ r, $ g = null, $ b = null)
Definition at line 393 of file fpdf.php.
References _out().
FPDF::SetFillColor ($ r, $ g = null, $ b = null)
Definition at line 404 of file fpdf.php.
References _out().
FPDF::SetFont ($ family, $ style = '', $ size = 0)
Definition at line 512 of file fpdf.php.
References $fpdf_charwidths, _getfontpath(), _out(), and Error().
Referenced by AddPage().
FPDF::SetFontSize ($ size)
Definition at line 574 of file fpdf.php.
References _out().
FPDF::SetKeywords ($ keywords, $ isUTF8 = false)
Definition at line 257 of file fpdf.php.
References $keywords, and _UTF8toUTF16().
FPDF::SetLeftMargin ($ margin)
Definition at line 183 of file fpdf.php.
FPDF::SetLineWidth ($ width)
Definition at line 438 of file fpdf.php.
References _out().
FPDF::SetLink ($ link, $ y = 0, $ page = -1)
Definition at line 593 of file fpdf.php.
References $page, and $y.
FPDF::SetMargins ($ left, $ top, $ right = null)
Definition at line 173 of file fpdf.php.
Referenced by FPDF().
FPDF::SetRightMargin ($ margin)
Definition at line 197 of file fpdf.php.
FPDF::SetSubject ($ subject, $ isUTF8 = false)
Definition at line 241 of file fpdf.php.
References $subject, and _UTF8toUTF16().
FPDF::SetTextColor ($ r, $ g = null, $ b = null)
Definition at line 416 of file fpdf.php.
FPDF::SetTitle ($ title, $ isUTF8 = false)
Definition at line 233 of file fpdf.php.
References $title, and _UTF8toUTF16().
FPDF::SetTopMargin ($ margin)
Definition at line 191 of file fpdf.php.
FPDF::SetX ($ x)
Definition at line 971 of file fpdf.php.
References $x.
Referenced by SetXY().
FPDF::SetXY ($ x, $ y)
Definition at line 996 of file fpdf.php.
References $x, $y, SetX(), and SetY().
FPDF::SetY ($ y)
Definition at line 986 of file fpdf.php.
References $y.
Referenced by SetXY().
FPDF::Text ($ x, $ y, $ txt)
Definition at line 609 of file fpdf.php.
References $x, $y, _escape(), and _out().
FPDF::Write ($ h, $ txt, $ link = '')
Definition at line 818 of file fpdf.php.
References $h, $w, and Cell().
Member Data Documentation
FPDF::$AliasNbPages
Definition at line 78 of file fpdf.php.
FPDF::$author
Definition at line 75 of file fpdf.php.
Referenced by SetAuthor().
FPDF::$AutoPageBreak
Definition at line 67 of file fpdf.php.
FPDF::$bMargin
Definition at line 44 of file fpdf.php.
FPDF::$buffer
Definition at line 28 of file fpdf.php.
FPDF::$cMargin
Definition at line 45 of file fpdf.php.
FPDF::$ColorFlag
Definition at line 62 of file fpdf.php.
FPDF::$compress
Definition at line 31 of file fpdf.php.
Referenced by SetCompression().
FPDF::$CoreFonts
Definition at line 49 of file fpdf.php.
FPDF::$creator
Definition at line 77 of file fpdf.php.
Referenced by SetCreator().
FPDF::$CurOrientation
Definition at line 34 of file fpdf.php.
FPDF::$CurPageFormat
Definition at line 37 of file fpdf.php.
FPDF::$CurrentFont
Definition at line 56 of file fpdf.php.
FPDF::$DefOrientation
Definition at line 33 of file fpdf.php.
FPDF::$DefPageFormat
Definition at line 36 of file fpdf.php.
FPDF::$diffs
Definition at line 52 of file fpdf.php.
FPDF::$DrawColor
Definition at line 59 of file fpdf.php.
FPDF::$FillColor
Definition at line 60 of file fpdf.php.
FPDF::$FontFamily
Definition at line 53 of file fpdf.php.
FPDF::$FontFiles
Definition at line 51 of file fpdf.php.
FPDF::$fonts
Definition at line 50 of file fpdf.php.
FPDF::$FontSize
Definition at line 58 of file fpdf.php.
FPDF::$FontSizePt
Definition at line 57 of file fpdf.php.
FPDF::$FontStyle
Definition at line 54 of file fpdf.php.
FPDF::$h
Definition at line 40 of file fpdf.php.
Referenced by _parsepng(), Cell(), Image(), Link(), Ln(), MultiCell(), Rect(), and Write().
FPDF::$hPt
Definition at line 39 of file fpdf.php.
FPDF::$images
Definition at line 64 of file fpdf.php.
FPDF::$InFooter
Definition at line 70 of file fpdf.php.
FPDF::$InHeader
Definition at line 69 of file fpdf.php.
FPDF::$k
Definition at line 32 of file fpdf.php.
Referenced by Cell().
FPDF::$keywords
Definition at line 76 of file fpdf.php.
Referenced by SetKeywords().
FPDF::$lasth
Definition at line 47 of file fpdf.php.
FPDF::$LayoutMode
Definition at line 72 of file fpdf.php.
FPDF::$LineWidth
Definition at line 48 of file fpdf.php.
FPDF::$links
Definition at line 66 of file fpdf.php.
FPDF::$lMargin
Definition at line 41 of file fpdf.php.
FPDF::$n
Definition at line 26 of file fpdf.php.
Referenced by _parsepng(), and AddLink().
FPDF::$offsets
Definition at line 27 of file fpdf.php.
FPDF::$page
Definition at line 25 of file fpdf.php.
Referenced by SetLink().
FPDF::$PageBreakTrigger
Definition at line 68 of file fpdf.php.
FPDF::$PageFormats
Definition at line 35 of file fpdf.php.
FPDF::$PageLinks
Definition at line 65 of file fpdf.php.
FPDF::$pages
Definition at line 29 of file fpdf.php.
FPDF::$PageSizes
Definition at line 38 of file fpdf.php.
FPDF::$PDFVersion
Definition at line 79 of file fpdf.php.
FPDF::$rMargin
Definition at line 43 of file fpdf.php.
FPDF::$state
Definition at line 30 of file fpdf.php.
FPDF::$subject
Definition at line 74 of file fpdf.php.
Referenced by SetSubject().
FPDF::$TextColor
Definition at line 61 of file fpdf.php.
FPDF::$title
Definition at line 73 of file fpdf.php.
Referenced by SetTitle().
FPDF::$tMargin
Definition at line 42 of file fpdf.php.
FPDF::$underline
Definition at line 55 of file fpdf.php.
FPDF::$w
Definition at line 40 of file fpdf.php.
Referenced by _dounderline(), _parsepng(), Cell(), GetStringWidth(), Image(), Link(), MultiCell(), Rect(), and Write().
FPDF::$wPt
Definition at line 39 of file fpdf.php.
FPDF::$ws
Definition at line 63 of file fpdf.php.
Referenced by Cell().
FPDF::$x
Definition at line 46 of file fpdf.php.
Referenced by _dounderline(), Cell(), Image(), Link(), Rect(), SetX(), SetXY(), and Text().
FPDF::$y
Definition at line 46 of file fpdf.php.
Referenced by _dounderline(), Cell(), Image(), Link(), Rect(), SetLink(), SetXY(), SetY(), and Text().
FPDF::$ZoomMode
Definition at line 71 of file fpdf.php.