mailformplusplus: Filtreatment Class Reference
Filtreatment Class Reference
Public Member Functions
__construct ()
ft_integer ($input)
ft_float ($input)
ft_validdate ($str)
ft_email ($email)
ft_dbsql ($value, $db_type= 'MYSQL')
ft_strregex ($value, $regex, $cv=1)
ft_xss ($str, $charset= 'ISO-8859-1')
display_error ($mode=1)
Public Attributes
$minval = 0
$maxval = 0
$error = ''
Private Member Functions
ft_realcmp ($r1, $r2)
Detailed Description
Definition at line 29 of file Filtreatment.php.
Constructor & Destructor Documentation
Filtreatment::__construct ()
CONSTRUCTOR
do some settings at init
Parameters:
none
Returns:
void
Definition at line 43 of file Filtreatment.php.
Member Function Documentation
Filtreatment::display_error ($ mode = 1)
DISPLAY ERRORS
Parameters:
int $mode - if 1 then echo the string; if 2 then echo the string
Returns:
void
Definition at line 447 of file Filtreatment.php.
References ft_xss().
Filtreatment::ft_dbsql ($ value, $ db_type = 'MYSQL')
PREPARES THE INPUT FOR DATABASE
works with mysql/postgresql NOTE: mysql_real_escape_string() requires that a valid mysql connection (mysql_connect()) exists to work
Parameters:
string $value - email to validate
string $db_type - allow two constants MYSQL | PGSQL
Returns:
string|bool $value sanitized value
Definition at line 208 of file Filtreatment.php.
Filtreatment::ft_email ($ email)
VALIDATES AN EMAIL
implies RFC 2822
Parameters:
string $str - email to validate
Returns:
string|bool - the string itselfs only for valid email
Definition at line 164 of file Filtreatment.php.
Filtreatment::ft_float ($ input)
CHECKS FOR A FLOAT
if the $minval and|or $maxval are set, a comparison will be performed
Parameters:
int $input - what to check/transform
Returns:
int|bool
Definition at line 96 of file Filtreatment.php.
References ft_realcmp().
Filtreatment::ft_integer ($ input)
CHECKS FOR AN INTEGER
if the $minval and|or $maxval are set, a comparison will be performed
NOTE: because the function can return 0 also as a valid result, check with === the return value
Parameters:
int $input - what to check/transform
Returns:
int|bool
Definition at line 61 of file Filtreatment.php.
Filtreatment::ft_realcmp ($ r1, $ r2) [private]
REAL COMPARASION BETWEEN FLOATS
0 - for ==, 1 for r1 > r2, -1 for r1 '<' r2
Parameters:
float $r1
float $r2
Returns:
int
Definition at line 467 of file Filtreatment.php.
Referenced by ft_float().
Filtreatment::ft_strregex ($ value, $ regex, $ cv = 1)
WORKS ON A STRING WITH REGEX EXPRESSION
checks a string for specified characters
Parameters:
string $value - variable to sanitize
string $regex - is in a special form detailed below: it contains ONLY allowed characters, ANY other characters making invalid string it must NOT contain begin/end delimitators /[... ]/ eg: 0-9, 0-9A-Za-z, AERS
int $cv - 1 or 2
Returns:
string|bool return string if check succeed ($cv = 1) or string with replaced chars
Definition at line 240 of file Filtreatment.php.
Filtreatment::ft_validdate ($ str)
VALIDATES A DATE
must be in YYYY-MM-DD format
Parameters:
string $str - date in requested format
Returns:
string|bool - the string itselfs only for valid date
Definition at line 143 of file Filtreatment.php.
Filtreatment::ft_xss ($ str, $ charset = 'ISO-8859-1')
CLEANS AGAINST XSS
NOTE all credits goes to codeigniter.com
Parameters:
string $str - string to check
string $charset - character set (default ISO-8859-1)
Returns:
string|bool $value sanitized string
Definition at line 274 of file Filtreatment.php.
Referenced by display_error().
Member Data Documentation
Filtreatment::$error = ''
Definition at line 33 of file Filtreatment.php.
Filtreatment::$maxval = 0
Definition at line 32 of file Filtreatment.php.
Filtreatment::$minval = 0
Definition at line 31 of file Filtreatment.php.