mailformplusplus: F3_MailformPlusPlus_Controller_Backend Class Reference
F3_MailformPlusPlus_Controller_Backend Class Reference
Public Member Functions
__construct (F3_GimmeFive_Component_Manager $componentManager, F3_MailformPlusPlus_Configuration $configuration)
process ()
Protected Member Functions
init ()
deleteRecords ($uids)
generatePDF ($detailId)
generateCSV ($detailId)
generateCSVExportFieldsSelector ($params)
generatePDFExportFieldsSelector ($params)
getSelectionJS ()
generateFormatsSelector ($formats, $detailId)
showSingleView ($singleUid)
getErrorMessage ()
fetchRecords ()
buildWhereClause ()
dateToTimestamp ($date, $end=false)
getFilterSection ()
getCalendarJS ()
getTable (&$records)
Protected Attributes
$componentManager
$configuration
$logTable
Detailed Description
Definition at line 22 of file F3_MailformPlusPlus_Controller_Backend.php.
Constructor & Destructor Documentation
F3_MailformPlusPlus_Controller_Backend::__construct (F3_GimmeFive_Component_Manager $ componentManager, F3_MailformPlusPlus_Configuration $ configuration)
The constructor for a finisher setting the component manager and the configuration.
Parameters:
F3_GimmeFive_Component_Manager $componentManager
F3_MailformPlusPlus_Configuration $configuration
Author:
Reinhard Führicht <rf@typoheads.at>
Returns:
void
Definition at line 57 of file F3_MailformPlusPlus_Controller_Backend.php.
Member Function Documentation
F3_MailformPlusPlus_Controller_Backend::buildWhereClause () [protected]
This function applies the filter settings and builds an according WHERE clause for the SELECT statement
Returns:
string WHERE clause for the SELECT statement
Author:
Reinhard Führicht <rf@typoheads.at>
Definition at line 687 of file F3_MailformPlusPlus_Controller_Backend.php.
References dateToTimestamp().
Referenced by fetchRecords().
F3_MailformPlusPlus_Controller_Backend::dateToTimestamp ($ date, $ end = false) [protected]
This function formats a date
Parameters:
long $date The timestamp to format
boolean $end Is end date or start date
Returns:
string formatted date
Author:
Reinhard Führicht <rf@typoheads.at>
Definition at line 724 of file F3_MailformPlusPlus_Controller_Backend.php.
Referenced by buildWhereClause().
F3_MailformPlusPlus_Controller_Backend::deleteRecords ($ uids) [protected]
Function to delete one ore more records from log table
Parameters:
array $uids The record uids to delete
Returns:
void
Author:
Reinhard Führicht <rf@typoheads.at>
Definition at line 167 of file F3_MailformPlusPlus_Controller_Backend.php.
Referenced by process().
F3_MailformPlusPlus_Controller_Backend::fetchRecords () [protected]
This function selects all logged records from the log table using the filter settings.
Returns:
array The selected records
Author:
Reinhard Führicht <rf@typoheads.at>
Definition at line 661 of file F3_MailformPlusPlus_Controller_Backend.php.
References buildWhereClause().
Referenced by process().
F3_MailformPlusPlus_Controller_Backend::generateCSV ($ detailId) [protected]
Function to handle the generation of a CSV file. Before the data gets exported, the data is checked and the user gets informed about different formats of the data. Each format has to be exported in an own file. After the format selection, the user is able to select which fields to export in a selection view. This enables the user to get rid of fields like submitted or mp-step.
Parameters:
misc $detailId The record uids to export to csv
Returns:
void/string selection view
Author:
Reinhard Führicht <rf@typoheads.at>
Definition at line 240 of file F3_MailformPlusPlus_Controller_Backend.php.
References generateCSVExportFieldsSelector(), and generateFormatsSelector().
Referenced by process().
F3_MailformPlusPlus_Controller_Backend::generateCSVExportFieldsSelector ($ params) [protected]
This function returns a list of all available fields to export for CSV export. The user can choose several fields and start the export.
Parameters:
array $params The available fields to export.
Returns:
string fields selection view
Author:
Reinhard Führicht <rf@typoheads.at>
Definition at line 331 of file F3_MailformPlusPlus_Controller_Backend.php.
References getSelectionJS().
Referenced by generateCSV().
F3_MailformPlusPlus_Controller_Backend::generateFormatsSelector ($ formats, $ detailId) [protected]
This function returns a list of all available formats to export to CSV. The user has to choose one ny another and export them to different files.
Parameters:
array $formats The available formats
array $detailId The selected records to export
Returns:
string formats selection view
Author:
Reinhard Führicht <rf@typoheads.at>
Definition at line 505 of file F3_MailformPlusPlus_Controller_Backend.php.
Referenced by generateCSV().
F3_MailformPlusPlus_Controller_Backend::generatePDF ($ detailId) [protected]
Function to handle the generation of a PDF file. Before the data gets exported, the user is able to select which fields to export in a selection view. This enables the user to get rid of fields like submitted or mp-step.
Parameters:
misc $detailId The record uids to export to pdf
Returns:
void/string selection view
Author:
Reinhard Führicht
Definition at line 180 of file F3_MailformPlusPlus_Controller_Backend.php.
References generatePDFExportFieldsSelector().
Referenced by process().
F3_MailformPlusPlus_Controller_Backend::generatePDFExportFieldsSelector ($ params) [protected]
This function returns a list of all available fields to export for PDF export. The user can choose several fields and start the export.
Parameters:
array $params The available fields to export.
Returns:
string fields selection view
Author:
Reinhard Führicht <rf@typoheads.at>
Definition at line 401 of file F3_MailformPlusPlus_Controller_Backend.php.
References getSelectionJS().
Referenced by generatePDF().
F3_MailformPlusPlus_Controller_Backend::getCalendarJS () [protected]
This function returns the JavaScript code to initialize the popup calendar
Returns:
string HTML and JavaScript
Author:
Reinhard Führicht <rf@typoheads.at>
Definition at line 792 of file F3_MailformPlusPlus_Controller_Backend.php.
Referenced by getFilterSection().
F3_MailformPlusPlus_Controller_Backend::getErrorMessage () [protected]
This function returns an error message if the log table was not found
Returns:
string HTML code with error message
Author:
Reinhard Führicht <rf@typoheads.at>
Definition at line 638 of file F3_MailformPlusPlus_Controller_Backend.php.
Referenced by process().
F3_MailformPlusPlus_Controller_Backend::getFilterSection () [protected]
This function returns the filter fields on top.
Returns:
string HTML
Author:
Reinhard Führicht <rf@typoheads.at>
Definition at line 738 of file F3_MailformPlusPlus_Controller_Backend.php.
References getCalendarJS().
Referenced by getTable().
F3_MailformPlusPlus_Controller_Backend::getSelectionJS () [protected]
This function returns JavaScript code to select/deselect all checkboxes in a form
Returns:
string JavaScript code
Author:
Reinhard Führicht <rf@typoheads.at>
Definition at line 471 of file F3_MailformPlusPlus_Controller_Backend.php.
Referenced by generateCSVExportFieldsSelector(), generatePDFExportFieldsSelector(), and getTable().
F3_MailformPlusPlus_Controller_Backend::getTable (&$ records) [protected]
This function returns the index table.
Parameters:
array &$records The records to show in table
Returns:
string HTML
Author:
Reinhard Führicht <rf@typoheads.at>
Definition at line 825 of file F3_MailformPlusPlus_Controller_Backend.php.
References getFilterSection(), and getSelectionJS().
Referenced by process().
F3_MailformPlusPlus_Controller_Backend::init () [protected]
init method to load translation data and set log table.
$LANG
Returns:
void
Author:
Reinhard Führicht <rf@typoheads.at>
Definition at line 69 of file F3_MailformPlusPlus_Controller_Backend.php.
Referenced by process().
F3_MailformPlusPlus_Controller_Backend::process ()
Main method of the controller.
Returns:
string rendered view
Author:
Reinhard Führicht <rf@typoheads.at>
Implements F3_MailformPlusPlus_ControllerInterface.
Definition at line 81 of file F3_MailformPlusPlus_Controller_Backend.php.
References deleteRecords(), fetchRecords(), generateCSV(), generatePDF(), getErrorMessage(), getTable(), init(), and showSingleView().
F3_MailformPlusPlus_Controller_Backend::showSingleView ($ singleUid) [protected]
This function returns a single view of a record
Parameters:
int $singleUid The UID of the record to show
Returns:
string single view
Author:
Reinhard Führicht <rf@typoheads.at>
Definition at line 562 of file F3_MailformPlusPlus_Controller_Backend.php.
Referenced by process().
Member Data Documentation
F3_MailformPlusPlus_Controller_Backend::$componentManager [protected]
Definition at line 31 of file F3_MailformPlusPlus_Controller_Backend.php.
F3_MailformPlusPlus_Controller_Backend::$configuration [protected]
Definition at line 39 of file F3_MailformPlusPlus_Controller_Backend.php.
F3_MailformPlusPlus_Controller_Backend::$logTable [protected]
Definition at line 47 of file F3_MailformPlusPlus_Controller_Backend.php.