mailformplusplus: tx_MailformPlusPlus_Dispatcher Class Reference
tx_MailformPlusPlus_Dispatcher Class Reference
Public Member Functions
main ($content, $setup)
Protected Member Functions
handleAjax ()
parseEmailSettings ()
Private Member Functions
parseEmailSettingsByType ($type, $optionsToParse=array())
getFFvalue ($name, $section)
Detailed Description
Definition at line 27 of file tx_MailformPlusPlus_Dispatcher.php.
Member Function Documentation
tx_MailformPlusPlus_Dispatcher::getFFvalue ($ name, $ section) [private]
Reads a value from flexform data.
Parameters:
string $name Name of the flexform value
string $section Section in flexform where the value is stored
Returns:
string The requested value
Author:
Reinhard Führicht <rf@typoheads.at>
Definition at line 187 of file tx_MailformPlusPlus_Dispatcher.php.
Referenced by parseEmailSettingsByType().
tx_MailformPlusPlus_Dispatcher::handleAjax () [protected]
Adds JavaScript for xajax and registers callable methods. Passes AJAX requests to requested methods.
Returns:
void
Author:
Reinhard Führicht <rf@typoheads.at>
Definition at line 36 of file tx_MailformPlusPlus_Dispatcher.php.
Referenced by main().
tx_MailformPlusPlus_Dispatcher::main ($ content, $ setup)
Main method of the dispatcher. This method is called as a user function.
Returns:
string rendered view
Parameters:
string $content
array $setup The TypoScript config
Author:
Reinhard Führicht <rf@typoheads.at>
Definition at line 58 of file tx_MailformPlusPlus_Dispatcher.php.
References handleAjax(), and parseEmailSettings().
tx_MailformPlusPlus_Dispatcher::parseEmailSettings () [protected]
Parses the email settings in flexform and stores them in an array.
Returns:
array The parsed email settings
Author:
Reinhard Führicht <rf@typoheads.at>
Definition at line 130 of file tx_MailformPlusPlus_Dispatcher.php.
References parseEmailSettingsByType().
Referenced by main().
tx_MailformPlusPlus_Dispatcher::parseEmailSettingsByType ($ type, $ optionsToParse = array()) [private]
Parses the email settings in flexform of a specific type (admin|user]
Parameters:
string $type (admin|user)
array $optionsToParse Mapping array with flexform name as key and key in parsed array as value.
Returns:
array The parsed email settings
Author:
Reinhard Führicht <rf@typoheads.at>
Definition at line 162 of file tx_MailformPlusPlus_Dispatcher.php.
References getFFvalue().
Referenced by parseEmailSettings().