mailformplusplus: F3_MailformPlusPlus_View_Multistep Class Reference
F3_MailformPlusPlus_View_Multistep Class Reference
Protected Member Functions
parseSettings ()
fillDefaultMarkers ()
addHiddenFields (&$markers)
createStepBar ($currentStep, $lastStep, $buttonNameBack="", $buttonNameFwd="")
Detailed Description
Definition at line 24 of file F3_MailformPlusPlus_View_Multistep.php.
Member Function Documentation
F3_MailformPlusPlus_View_Multistep::addHiddenFields (&$ markers) [protected]
Adds the values stored in $_SESSION as hidden fields in marker ##ADDITIONAL_MULTISTEP###.
Needed in conditional forms.
Parameters:
array &$markers The markers to put the new one into
Returns:
void
Definition at line 111 of file F3_MailformPlusPlus_View_Multistep.php.
Referenced by fillDefaultMarkers().
F3_MailformPlusPlus_View_Multistep::createStepBar ($ currentStep, $ lastStep, $ buttonNameBack = "", $ buttonNameFwd = "") [protected]
copied from dam_index
Returns HTML of a box with a step counter and "back" and "next" buttons
Parameters:
integer $currentStep current step (begins with 1)
integer $lastStep last step
string $buttonNameBack name attribute of the back button
string $buttonNameFwd name attribute of the forward button
Returns:
string HTML code
Definition at line 149 of file F3_MailformPlusPlus_View_Multistep.php.
Referenced by fillDefaultMarkers().
F3_MailformPlusPlus_View_Multistep::fillDefaultMarkers () [protected]
Fill default markers of multistep forms
##curStep### ##maxStep### ##lastStep### ##submit_nextStep### ##submit_prevStep### ##submit_reload### ##step_bar###
Parameters:
integer $currentStep current step (begins with 1)
integer $lastStep last step
string $buttonNameBack name attribute of the back button
string $buttonNameFwd name attribute of the forward button
Returns:
void
Reimplemented from F3_MailformPlusPlus_View_Default.
Definition at line 55 of file F3_MailformPlusPlus_View_Multistep.php.
References addHiddenFields(), and createStepBar().
F3_MailformPlusPlus_View_Multistep::parseSettings () [protected]
Get the right settings for current step.
Returns:
array The settings
Reimplemented from F3_MailformPlusPlus_View_Default.
Definition at line 31 of file F3_MailformPlusPlus_View_Multistep.php.